/*
IP Address Management API

The IPAM/DHCP Application is a Universal DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"encoding/json"
	"fmt"
)

// checks if the SyslogServer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyslogServer{}

// SyslogServer External Syslog server to forward the DHCP queries and logs.
type SyslogServer struct {
	// Syslog Server IP address.
	Address string `json:"address"`
	// Syslog Server Port.  Defaults to 514.
	Port int64 `json:"port"`
	// Read only. Syslog Server Protocol. Value is always _UDP_.
	Protocol             *string `json:"protocol,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SyslogServer SyslogServer

// NewSyslogServer instantiates a new SyslogServer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyslogServer(address string, port int64) *SyslogServer {
	this := SyslogServer{}
	this.Address = address
	this.Port = port
	return &this
}

// NewSyslogServerWithDefaults instantiates a new SyslogServer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyslogServerWithDefaults() *SyslogServer {
	this := SyslogServer{}
	return &this
}

// GetAddress returns the Address field value
func (o *SyslogServer) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *SyslogServer) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *SyslogServer) SetAddress(v string) {
	o.Address = v
}

// GetPort returns the Port field value
func (o *SyslogServer) GetPort() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *SyslogServer) GetPortOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *SyslogServer) SetPort(v int64) {
	o.Port = v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *SyslogServer) GetProtocol() string {
	if o == nil || IsNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SyslogServer) GetProtocolOk() (*string, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *SyslogServer) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *SyslogServer) SetProtocol(v string) {
	o.Protocol = &v
}

func (o SyslogServer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyslogServer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["port"] = o.Port
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SyslogServer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
		"port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyslogServer := _SyslogServer{}

	err = json.Unmarshal(data, &varSyslogServer)

	if err != nil {
		return err
	}

	*o = SyslogServer(varSyslogServer)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "port")
		delete(additionalProperties, "protocol")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSyslogServer struct {
	value *SyslogServer
	isSet bool
}

func (v NullableSyslogServer) Get() *SyslogServer {
	return v.value
}

func (v *NullableSyslogServer) Set(val *SyslogServer) {
	v.value = val
	v.isSet = true
}

func (v NullableSyslogServer) IsSet() bool {
	return v.isSet
}

func (v *NullableSyslogServer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyslogServer(val *SyslogServer) *NullableSyslogServer {
	return &NullableSyslogServer{value: val, isSet: true}
}

func (v NullableSyslogServer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyslogServer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
