/*
IP Address Management API

The IPAM/DHCP Application is a Universal DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"encoding/json"
)

// checks if the LoggingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LoggingConfig{}

// LoggingConfig Configuration for external logging servers.
type LoggingConfig struct {
	// Optional. List of syslog servers.
	SyslogServers        []SyslogServer `json:"syslog_servers,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LoggingConfig LoggingConfig

// NewLoggingConfig instantiates a new LoggingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoggingConfig() *LoggingConfig {
	this := LoggingConfig{}
	return &this
}

// NewLoggingConfigWithDefaults instantiates a new LoggingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoggingConfigWithDefaults() *LoggingConfig {
	this := LoggingConfig{}
	return &this
}

// GetSyslogServers returns the SyslogServers field value if set, zero value otherwise.
func (o *LoggingConfig) GetSyslogServers() []SyslogServer {
	if o == nil || IsNil(o.SyslogServers) {
		var ret []SyslogServer
		return ret
	}
	return o.SyslogServers
}

// GetSyslogServersOk returns a tuple with the SyslogServers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoggingConfig) GetSyslogServersOk() ([]SyslogServer, bool) {
	if o == nil || IsNil(o.SyslogServers) {
		return nil, false
	}
	return o.SyslogServers, true
}

// HasSyslogServers returns a boolean if a field has been set.
func (o *LoggingConfig) HasSyslogServers() bool {
	if o != nil && !IsNil(o.SyslogServers) {
		return true
	}

	return false
}

// SetSyslogServers gets a reference to the given []SyslogServer and assigns it to the SyslogServers field.
func (o *LoggingConfig) SetSyslogServers(v []SyslogServer) {
	o.SyslogServers = v
}

func (o LoggingConfig) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LoggingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SyslogServers) {
		toSerialize["syslog_servers"] = o.SyslogServers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LoggingConfig) UnmarshalJSON(data []byte) (err error) {
	varLoggingConfig := _LoggingConfig{}

	err = json.Unmarshal(data, &varLoggingConfig)

	if err != nil {
		return err
	}

	*o = LoggingConfig(varLoggingConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "syslog_servers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLoggingConfig struct {
	value *LoggingConfig
	isSet bool
}

func (v NullableLoggingConfig) Get() *LoggingConfig {
	return v.value
}

func (v *NullableLoggingConfig) Set(val *LoggingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableLoggingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableLoggingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoggingConfig(val *LoggingConfig) *NullableLoggingConfig {
	return &NullableLoggingConfig{value: val, isSet: true}
}

func (v NullableLoggingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoggingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
