/*
IP Address Management API

The IPAM/DHCP Application is a Universal DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"encoding/json"
)

// checks if the GetSharedNetworkSubnetsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSharedNetworkSubnetsResponse{}

// GetSharedNetworkSubnetsResponse The response format to retrieve the subnet members of a __SharedNetwork__ object.
type GetSharedNetworkSubnetsResponse struct {
	// The list of subnets that are members of the shared network.
	Results              []SharedNetworkSubnet `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetSharedNetworkSubnetsResponse GetSharedNetworkSubnetsResponse

// NewGetSharedNetworkSubnetsResponse instantiates a new GetSharedNetworkSubnetsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSharedNetworkSubnetsResponse() *GetSharedNetworkSubnetsResponse {
	this := GetSharedNetworkSubnetsResponse{}
	return &this
}

// NewGetSharedNetworkSubnetsResponseWithDefaults instantiates a new GetSharedNetworkSubnetsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSharedNetworkSubnetsResponseWithDefaults() *GetSharedNetworkSubnetsResponse {
	this := GetSharedNetworkSubnetsResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetSharedNetworkSubnetsResponse) GetResults() []SharedNetworkSubnet {
	if o == nil || IsNil(o.Results) {
		var ret []SharedNetworkSubnet
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSharedNetworkSubnetsResponse) GetResultsOk() ([]SharedNetworkSubnet, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetSharedNetworkSubnetsResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []SharedNetworkSubnet and assigns it to the Results field.
func (o *GetSharedNetworkSubnetsResponse) SetResults(v []SharedNetworkSubnet) {
	o.Results = v
}

func (o GetSharedNetworkSubnetsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSharedNetworkSubnetsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetSharedNetworkSubnetsResponse) UnmarshalJSON(data []byte) (err error) {
	varGetSharedNetworkSubnetsResponse := _GetSharedNetworkSubnetsResponse{}

	err = json.Unmarshal(data, &varGetSharedNetworkSubnetsResponse)

	if err != nil {
		return err
	}

	*o = GetSharedNetworkSubnetsResponse(varGetSharedNetworkSubnetsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetSharedNetworkSubnetsResponse struct {
	value *GetSharedNetworkSubnetsResponse
	isSet bool
}

func (v NullableGetSharedNetworkSubnetsResponse) Get() *GetSharedNetworkSubnetsResponse {
	return v.value
}

func (v *NullableGetSharedNetworkSubnetsResponse) Set(val *GetSharedNetworkSubnetsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSharedNetworkSubnetsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSharedNetworkSubnetsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSharedNetworkSubnetsResponse(val *GetSharedNetworkSubnetsResponse) *NullableGetSharedNetworkSubnetsResponse {
	return &NullableGetSharedNetworkSubnetsResponse{value: val, isSet: true}
}

func (v NullableGetSharedNetworkSubnetsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSharedNetworkSubnetsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
