/*
IP Address Management API

The IPAM/DHCP Application is a Universal DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"encoding/json"
)

// checks if the LinkedHAGroupsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkedHAGroupsResponse{}

// LinkedHAGroupsResponse The response format to retrieve the list of linked HA groups.
type LinkedHAGroupsResponse struct {
	// The number of HA groups each host belongs to. Host is provided in the request, either implicitly via HA group reference or directly via list of host references.
	HostHaGroupCounts []HostHAGroupCount `json:"host_ha_group_counts,omitempty"`
	// The list of linked HA group objects.
	Results              []LinkedHAGroup `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _LinkedHAGroupsResponse LinkedHAGroupsResponse

// NewLinkedHAGroupsResponse instantiates a new LinkedHAGroupsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkedHAGroupsResponse() *LinkedHAGroupsResponse {
	this := LinkedHAGroupsResponse{}
	return &this
}

// NewLinkedHAGroupsResponseWithDefaults instantiates a new LinkedHAGroupsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkedHAGroupsResponseWithDefaults() *LinkedHAGroupsResponse {
	this := LinkedHAGroupsResponse{}
	return &this
}

// GetHostHaGroupCounts returns the HostHaGroupCounts field value if set, zero value otherwise.
func (o *LinkedHAGroupsResponse) GetHostHaGroupCounts() []HostHAGroupCount {
	if o == nil || IsNil(o.HostHaGroupCounts) {
		var ret []HostHAGroupCount
		return ret
	}
	return o.HostHaGroupCounts
}

// GetHostHaGroupCountsOk returns a tuple with the HostHaGroupCounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkedHAGroupsResponse) GetHostHaGroupCountsOk() ([]HostHAGroupCount, bool) {
	if o == nil || IsNil(o.HostHaGroupCounts) {
		return nil, false
	}
	return o.HostHaGroupCounts, true
}

// HasHostHaGroupCounts returns a boolean if a field has been set.
func (o *LinkedHAGroupsResponse) HasHostHaGroupCounts() bool {
	if o != nil && !IsNil(o.HostHaGroupCounts) {
		return true
	}

	return false
}

// SetHostHaGroupCounts gets a reference to the given []HostHAGroupCount and assigns it to the HostHaGroupCounts field.
func (o *LinkedHAGroupsResponse) SetHostHaGroupCounts(v []HostHAGroupCount) {
	o.HostHaGroupCounts = v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *LinkedHAGroupsResponse) GetResults() []LinkedHAGroup {
	if o == nil || IsNil(o.Results) {
		var ret []LinkedHAGroup
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkedHAGroupsResponse) GetResultsOk() ([]LinkedHAGroup, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *LinkedHAGroupsResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []LinkedHAGroup and assigns it to the Results field.
func (o *LinkedHAGroupsResponse) SetResults(v []LinkedHAGroup) {
	o.Results = v
}

func (o LinkedHAGroupsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkedHAGroupsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HostHaGroupCounts) {
		toSerialize["host_ha_group_counts"] = o.HostHaGroupCounts
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LinkedHAGroupsResponse) UnmarshalJSON(data []byte) (err error) {
	varLinkedHAGroupsResponse := _LinkedHAGroupsResponse{}

	err = json.Unmarshal(data, &varLinkedHAGroupsResponse)

	if err != nil {
		return err
	}

	*o = LinkedHAGroupsResponse(varLinkedHAGroupsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "host_ha_group_counts")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLinkedHAGroupsResponse struct {
	value *LinkedHAGroupsResponse
	isSet bool
}

func (v NullableLinkedHAGroupsResponse) Get() *LinkedHAGroupsResponse {
	return v.value
}

func (v *NullableLinkedHAGroupsResponse) Set(val *LinkedHAGroupsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkedHAGroupsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkedHAGroupsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkedHAGroupsResponse(val *LinkedHAGroupsResponse) *NullableLinkedHAGroupsResponse {
	return &NullableLinkedHAGroupsResponse{value: val, isSet: true}
}

func (v NullableLinkedHAGroupsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkedHAGroupsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
