/*
IP Address Management API

The IPAM/DHCP Application is a Universal DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"encoding/json"
)

// checks if the ExportQueryParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportQueryParams{}

// ExportQueryParams Optional perspective-table query parameters for an export request.
type ExportQueryParams struct {
	// cidr_block filters the export results to objects within the given CIDR notation (e.g. \"10.0.0.0/8\").
	CidrBlock *string `json:"cidr_block,omitempty"`
	// fts is an optional full-text search query string used to restrict export results to objects whose searchable fields contain the given value.
	Fts *string `json:"fts,omitempty"`
	// node is the resource identifier used to scope the export query. For the _subnet_ view it should be the IP space ID or realm ID.
	Node *string `json:"node,omitempty"`
	// perspective_type specifies how IP space objects are grouped. Allowed values are: * _network_, * _location_, * _address_.
	PerspectiveType *string `json:"perspective_type,omitempty"`
	// state filters address results by allocation state. Allowed values are: * _free_, * _used_, * _any_.
	State *string `json:"state,omitempty"`
	// tfilter is an optional tag filter expression (for example, `key==\"value\"`) used to restrict export results to objects whose tags match the expression.
	Tfilter *string `json:"tfilter,omitempty"`
	// view specifies the perspective table view type. Allowed values are: * _subnet_, * _rangeaddress_, * _flataddress_, * _all_. Defaults to _subnet_ when not specified.
	View                 *string `json:"view,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExportQueryParams ExportQueryParams

// NewExportQueryParams instantiates a new ExportQueryParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportQueryParams() *ExportQueryParams {
	this := ExportQueryParams{}
	return &this
}

// NewExportQueryParamsWithDefaults instantiates a new ExportQueryParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportQueryParamsWithDefaults() *ExportQueryParams {
	this := ExportQueryParams{}
	return &this
}

// GetCidrBlock returns the CidrBlock field value if set, zero value otherwise.
func (o *ExportQueryParams) GetCidrBlock() string {
	if o == nil || IsNil(o.CidrBlock) {
		var ret string
		return ret
	}
	return *o.CidrBlock
}

// GetCidrBlockOk returns a tuple with the CidrBlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetCidrBlockOk() (*string, bool) {
	if o == nil || IsNil(o.CidrBlock) {
		return nil, false
	}
	return o.CidrBlock, true
}

// HasCidrBlock returns a boolean if a field has been set.
func (o *ExportQueryParams) HasCidrBlock() bool {
	if o != nil && !IsNil(o.CidrBlock) {
		return true
	}

	return false
}

// SetCidrBlock gets a reference to the given string and assigns it to the CidrBlock field.
func (o *ExportQueryParams) SetCidrBlock(v string) {
	o.CidrBlock = &v
}

// GetFts returns the Fts field value if set, zero value otherwise.
func (o *ExportQueryParams) GetFts() string {
	if o == nil || IsNil(o.Fts) {
		var ret string
		return ret
	}
	return *o.Fts
}

// GetFtsOk returns a tuple with the Fts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetFtsOk() (*string, bool) {
	if o == nil || IsNil(o.Fts) {
		return nil, false
	}
	return o.Fts, true
}

// HasFts returns a boolean if a field has been set.
func (o *ExportQueryParams) HasFts() bool {
	if o != nil && !IsNil(o.Fts) {
		return true
	}

	return false
}

// SetFts gets a reference to the given string and assigns it to the Fts field.
func (o *ExportQueryParams) SetFts(v string) {
	o.Fts = &v
}

// GetNode returns the Node field value if set, zero value otherwise.
func (o *ExportQueryParams) GetNode() string {
	if o == nil || IsNil(o.Node) {
		var ret string
		return ret
	}
	return *o.Node
}

// GetNodeOk returns a tuple with the Node field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetNodeOk() (*string, bool) {
	if o == nil || IsNil(o.Node) {
		return nil, false
	}
	return o.Node, true
}

// HasNode returns a boolean if a field has been set.
func (o *ExportQueryParams) HasNode() bool {
	if o != nil && !IsNil(o.Node) {
		return true
	}

	return false
}

// SetNode gets a reference to the given string and assigns it to the Node field.
func (o *ExportQueryParams) SetNode(v string) {
	o.Node = &v
}

// GetPerspectiveType returns the PerspectiveType field value if set, zero value otherwise.
func (o *ExportQueryParams) GetPerspectiveType() string {
	if o == nil || IsNil(o.PerspectiveType) {
		var ret string
		return ret
	}
	return *o.PerspectiveType
}

// GetPerspectiveTypeOk returns a tuple with the PerspectiveType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetPerspectiveTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PerspectiveType) {
		return nil, false
	}
	return o.PerspectiveType, true
}

// HasPerspectiveType returns a boolean if a field has been set.
func (o *ExportQueryParams) HasPerspectiveType() bool {
	if o != nil && !IsNil(o.PerspectiveType) {
		return true
	}

	return false
}

// SetPerspectiveType gets a reference to the given string and assigns it to the PerspectiveType field.
func (o *ExportQueryParams) SetPerspectiveType(v string) {
	o.PerspectiveType = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ExportQueryParams) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ExportQueryParams) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ExportQueryParams) SetState(v string) {
	o.State = &v
}

// GetTfilter returns the Tfilter field value if set, zero value otherwise.
func (o *ExportQueryParams) GetTfilter() string {
	if o == nil || IsNil(o.Tfilter) {
		var ret string
		return ret
	}
	return *o.Tfilter
}

// GetTfilterOk returns a tuple with the Tfilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetTfilterOk() (*string, bool) {
	if o == nil || IsNil(o.Tfilter) {
		return nil, false
	}
	return o.Tfilter, true
}

// HasTfilter returns a boolean if a field has been set.
func (o *ExportQueryParams) HasTfilter() bool {
	if o != nil && !IsNil(o.Tfilter) {
		return true
	}

	return false
}

// SetTfilter gets a reference to the given string and assigns it to the Tfilter field.
func (o *ExportQueryParams) SetTfilter(v string) {
	o.Tfilter = &v
}

// GetView returns the View field value if set, zero value otherwise.
func (o *ExportQueryParams) GetView() string {
	if o == nil || IsNil(o.View) {
		var ret string
		return ret
	}
	return *o.View
}

// GetViewOk returns a tuple with the View field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportQueryParams) GetViewOk() (*string, bool) {
	if o == nil || IsNil(o.View) {
		return nil, false
	}
	return o.View, true
}

// HasView returns a boolean if a field has been set.
func (o *ExportQueryParams) HasView() bool {
	if o != nil && !IsNil(o.View) {
		return true
	}

	return false
}

// SetView gets a reference to the given string and assigns it to the View field.
func (o *ExportQueryParams) SetView(v string) {
	o.View = &v
}

func (o ExportQueryParams) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportQueryParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CidrBlock) {
		toSerialize["cidr_block"] = o.CidrBlock
	}
	if !IsNil(o.Fts) {
		toSerialize["fts"] = o.Fts
	}
	if !IsNil(o.Node) {
		toSerialize["node"] = o.Node
	}
	if !IsNil(o.PerspectiveType) {
		toSerialize["perspective_type"] = o.PerspectiveType
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Tfilter) {
		toSerialize["tfilter"] = o.Tfilter
	}
	if !IsNil(o.View) {
		toSerialize["view"] = o.View
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExportQueryParams) UnmarshalJSON(data []byte) (err error) {
	varExportQueryParams := _ExportQueryParams{}

	err = json.Unmarshal(data, &varExportQueryParams)

	if err != nil {
		return err
	}

	*o = ExportQueryParams(varExportQueryParams)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cidr_block")
		delete(additionalProperties, "fts")
		delete(additionalProperties, "node")
		delete(additionalProperties, "perspective_type")
		delete(additionalProperties, "state")
		delete(additionalProperties, "tfilter")
		delete(additionalProperties, "view")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExportQueryParams struct {
	value *ExportQueryParams
	isSet bool
}

func (v NullableExportQueryParams) Get() *ExportQueryParams {
	return v.value
}

func (v *NullableExportQueryParams) Set(val *ExportQueryParams) {
	v.value = val
	v.isSet = true
}

func (v NullableExportQueryParams) IsSet() bool {
	return v.isSet
}

func (v *NullableExportQueryParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportQueryParams(val *ExportQueryParams) *NullableExportQueryParams {
	return &NullableExportQueryParams{value: val, isSet: true}
}

func (v NullableExportQueryParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportQueryParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
