/*
IP Address Management API

The IPAM/DHCP Application is a Universal DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"encoding/json"
)

// checks if the CreateSharedNetworkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateSharedNetworkResponse{}

// CreateSharedNetworkResponse The response format to create the __SharedNetwork__ object.
type CreateSharedNetworkResponse struct {
	// The created SharedNetwork object.
	Result               *SharedNetwork `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateSharedNetworkResponse CreateSharedNetworkResponse

// NewCreateSharedNetworkResponse instantiates a new CreateSharedNetworkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateSharedNetworkResponse() *CreateSharedNetworkResponse {
	this := CreateSharedNetworkResponse{}
	return &this
}

// NewCreateSharedNetworkResponseWithDefaults instantiates a new CreateSharedNetworkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateSharedNetworkResponseWithDefaults() *CreateSharedNetworkResponse {
	this := CreateSharedNetworkResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CreateSharedNetworkResponse) GetResult() SharedNetwork {
	if o == nil || IsNil(o.Result) {
		var ret SharedNetwork
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateSharedNetworkResponse) GetResultOk() (*SharedNetwork, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CreateSharedNetworkResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given SharedNetwork and assigns it to the Result field.
func (o *CreateSharedNetworkResponse) SetResult(v SharedNetwork) {
	o.Result = &v
}

func (o CreateSharedNetworkResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateSharedNetworkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateSharedNetworkResponse) UnmarshalJSON(data []byte) (err error) {
	varCreateSharedNetworkResponse := _CreateSharedNetworkResponse{}

	err = json.Unmarshal(data, &varCreateSharedNetworkResponse)

	if err != nil {
		return err
	}

	*o = CreateSharedNetworkResponse(varCreateSharedNetworkResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateSharedNetworkResponse struct {
	value *CreateSharedNetworkResponse
	isSet bool
}

func (v NullableCreateSharedNetworkResponse) Get() *CreateSharedNetworkResponse {
	return v.value
}

func (v *NullableCreateSharedNetworkResponse) Set(val *CreateSharedNetworkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateSharedNetworkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateSharedNetworkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateSharedNetworkResponse(val *CreateSharedNetworkResponse) *NullableCreateSharedNetworkResponse {
	return &NullableCreateSharedNetworkResponse{value: val, isSet: true}
}

func (v NullableCreateSharedNetworkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateSharedNetworkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
