/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"

	"github.com/infobloxopen/universal-ddi-go-client/internal"
)

type AccountsAPI interface {
	/*
		AccountListGroups Method for AccountListGroups

		List groups in the current account. Note: the bypass_entitlement_filtering parameter has no effect on this endpoint.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return AccountsAPIAccountListGroupsRequest
	*/
	AccountListGroups(ctx context.Context) AccountsAPIAccountListGroupsRequest

	// AccountListGroupsExecute executes the request
	//  @return AccountListGroupsResponse
	AccountListGroupsExecute(r AccountsAPIAccountListGroupsRequest) (*AccountListGroupsResponse, *http.Response, error)
	/*
		AccountListUsers Method for AccountListUsers

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return AccountsAPIAccountListUsersRequest
	*/
	AccountListUsers(ctx context.Context) AccountsAPIAccountListUsersRequest

	// AccountListUsersExecute executes the request
	//  @return AccountListUsersResponse
	AccountListUsersExecute(r AccountsAPIAccountListUsersRequest) (*AccountListUsersResponse, *http.Response, error)
	/*
		CurrentAccountGet Method for CurrentAccountGet

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return AccountsAPICurrentAccountGetRequest
	*/
	CurrentAccountGet(ctx context.Context) AccountsAPICurrentAccountGetRequest

	// CurrentAccountGetExecute executes the request
	//  @return AccountGetResponse
	CurrentAccountGetExecute(r AccountsAPICurrentAccountGetRequest) (*AccountGetResponse, *http.Response, error)
}

// AccountsAPIService AccountsAPI service
type AccountsAPIService internal.Service

type AccountsAPIAccountListGroupsRequest struct {
	ctx                        context.Context
	ApiService                 AccountsAPI
	filter                     *string
	orderBy                    *string
	offset                     *int32
	limit                      *int32
	pageToken                  *string
	fields                     *string
	bypassEntitlementFiltering *bool
	checkFeatureFlag           *bool
}

// A collection of response resources can be filtered by a logical expression string that includes JSON tag references to values in each resource, literal values, and logical operators. If a resource does not have the specified tag, its value is assumed to be null.  Literal values include numbers (integer and floating-point), and quoted (both single- or double-quoted) literal strings, and &#39;null&#39;. The following operators are commonly used in filter expressions:  |  Op   |  Description               |  |  --   |  -----------               |  |  &#x3D;&#x3D;   |  Equal                     |  |  !&#x3D;   |  Not Equal                 |  |  &gt;    |  Greater Than              |  |   &gt;&#x3D;  |  Greater Than or Equal To  |  |  &lt;    |  Less Than                 |  |  &lt;&#x3D;   |  Less Than or Equal To     |  |  and  |  Logical AND               |  |  ~    |  Matches Regex             |  |  !~   |  Does Not Match Regex      |  |  or   |  Logical OR                |  |  not  |  Logical NOT               |  |  ()   |  Groupping Operators       |
func (r AccountsAPIAccountListGroupsRequest) Filter(filter string) AccountsAPIAccountListGroupsRequest {
	r.filter = &filter
	return r
}

// A collection of response resources can be sorted by their JSON tags. For a &#39;flat&#39; resource, the tag name is straightforward. If sorting is allowed on non-flat hierarchical resources, the service should implement a qualified naming scheme such as dot-qualification to reference data down the hierarchy. If a resource does not have the specified tag, its value is assumed to be null.)  Specify this parameter as a comma-separated list of JSON tag names. The sort direction can be specified by a suffix separated by whitespace before the tag name. The suffix &#39;asc&#39; sorts the data in ascending order. The suffix &#39;desc&#39; sorts the data in descending order. If no suffix is specified the data is sorted in ascending order.
func (r AccountsAPIAccountListGroupsRequest) OrderBy(orderBy string) AccountsAPIAccountListGroupsRequest {
	r.orderBy = &orderBy
	return r
}

// The integer index (zero-origin) of the offset into a collection of resources. If omitted or null the value is assumed to be &#39;0&#39;.
func (r AccountsAPIAccountListGroupsRequest) Offset(offset int32) AccountsAPIAccountListGroupsRequest {
	r.offset = &offset
	return r
}

// The integer number of resources to be returned in the response. The service may impose maximum value. If omitted the service may impose a default value.
func (r AccountsAPIAccountListGroupsRequest) Limit(limit int32) AccountsAPIAccountListGroupsRequest {
	r.limit = &limit
	return r
}

// The service-defined string used to identify a page of resources. A null value indicates the first page.
func (r AccountsAPIAccountListGroupsRequest) PageToken(pageToken string) AccountsAPIAccountListGroupsRequest {
	r.pageToken = &pageToken
	return r
}

// A collection of response resources can be transformed by specifying a set of JSON tags to be returned. For a “flat” resource, the tag name is straightforward. If field selection is allowed on non-flat hierarchical resources, the service should implement a qualified naming scheme such as dot-qualification to reference data down the hierarchy. If a resource does not have the specified tag, the tag does not appear in the output resource.  Specify this parameter as a comma-separated list of JSON tag names.
func (r AccountsAPIAccountListGroupsRequest) Fields(fields string) AccountsAPIAccountListGroupsRequest {
	r.fields = &fields
	return r
}

// When true, entitlement-based filtering of groups is skipped and all groups for the account are returned. Defaults to false (i.e. entitlement filtering is applied). NOTE: Only takes effect on private (SaaS) endpoints; silently ignored on public endpoints that share this request type.
func (r AccountsAPIAccountListGroupsRequest) BypassEntitlementFiltering(bypassEntitlementFiltering bool) AccountsAPIAccountListGroupsRequest {
	r.bypassEntitlementFiltering = &bypassEntitlementFiltering
	return r
}

// When true, groups gated behind a feature flag are filtered by whether that flag is enabled for the owning account. Defaults to false (no FF filtering). NOTE: Only takes effect on private (SaaS) endpoints; silently ignored on public endpoints that share this request type.
func (r AccountsAPIAccountListGroupsRequest) CheckFeatureFlag(checkFeatureFlag bool) AccountsAPIAccountListGroupsRequest {
	r.checkFeatureFlag = &checkFeatureFlag
	return r
}

func (r AccountsAPIAccountListGroupsRequest) Execute() (*AccountListGroupsResponse, *http.Response, error) {
	return r.ApiService.AccountListGroupsExecute(r)
}

/*
AccountListGroups Method for AccountListGroups

List groups in the current account. Note: the bypass_entitlement_filtering parameter has no effect on this endpoint.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AccountsAPIAccountListGroupsRequest
*/
func (a *AccountsAPIService) AccountListGroups(ctx context.Context) AccountsAPIAccountListGroupsRequest {
	return AccountsAPIAccountListGroupsRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AccountListGroupsResponse
func (a *AccountsAPIService) AccountListGroupsExecute(r AccountsAPIAccountListGroupsRequest) (*AccountListGroupsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *AccountListGroupsResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "AccountsAPIService.AccountListGroups")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/accounts/groups"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.filter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_filter", r.filter, "")
	}
	if r.orderBy != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_order_by", r.orderBy, "")
	}
	if r.offset != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_offset", r.offset, "")
	}
	if r.limit != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_limit", r.limit, "")
	}
	if r.pageToken != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_token", r.pageToken, "")
	}
	if r.fields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_fields", r.fields, "")
	}
	if r.bypassEntitlementFiltering != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "bypass_entitlement_filtering", r.bypassEntitlementFiltering, "")
	}
	if r.checkFeatureFlag != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "check_feature_flag", r.checkFeatureFlag, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountsAPIAccountListUsersRequest struct {
	ctx        context.Context
	ApiService AccountsAPI
	filter     *string
	orderBy    *string
	offset     *int32
	limit      *int32
	pageToken  *string
	fields     *string
}

// A collection of response resources can be filtered by a logical expression string that includes JSON tag references to values in each resource, literal values, and logical operators. If a resource does not have the specified tag, its value is assumed to be null.  Literal values include numbers (integer and floating-point), and quoted (both single- or double-quoted) literal strings, and &#39;null&#39;. The following operators are commonly used in filter expressions:  |  Op   |  Description               |  |  --   |  -----------               |  |  &#x3D;&#x3D;   |  Equal                     |  |  !&#x3D;   |  Not Equal                 |  |  &gt;    |  Greater Than              |  |   &gt;&#x3D;  |  Greater Than or Equal To  |  |  &lt;    |  Less Than                 |  |  &lt;&#x3D;   |  Less Than or Equal To     |  |  and  |  Logical AND               |  |  ~    |  Matches Regex             |  |  !~   |  Does Not Match Regex      |  |  or   |  Logical OR                |  |  not  |  Logical NOT               |  |  ()   |  Groupping Operators       |
func (r AccountsAPIAccountListUsersRequest) Filter(filter string) AccountsAPIAccountListUsersRequest {
	r.filter = &filter
	return r
}

// A collection of response resources can be sorted by their JSON tags. For a &#39;flat&#39; resource, the tag name is straightforward. If sorting is allowed on non-flat hierarchical resources, the service should implement a qualified naming scheme such as dot-qualification to reference data down the hierarchy. If a resource does not have the specified tag, its value is assumed to be null.)  Specify this parameter as a comma-separated list of JSON tag names. The sort direction can be specified by a suffix separated by whitespace before the tag name. The suffix &#39;asc&#39; sorts the data in ascending order. The suffix &#39;desc&#39; sorts the data in descending order. If no suffix is specified the data is sorted in ascending order.
func (r AccountsAPIAccountListUsersRequest) OrderBy(orderBy string) AccountsAPIAccountListUsersRequest {
	r.orderBy = &orderBy
	return r
}

// The integer index (zero-origin) of the offset into a collection of resources. If omitted or null the value is assumed to be &#39;0&#39;.
func (r AccountsAPIAccountListUsersRequest) Offset(offset int32) AccountsAPIAccountListUsersRequest {
	r.offset = &offset
	return r
}

// The integer number of resources to be returned in the response. The service may impose maximum value. If omitted the service may impose a default value.
func (r AccountsAPIAccountListUsersRequest) Limit(limit int32) AccountsAPIAccountListUsersRequest {
	r.limit = &limit
	return r
}

// The service-defined string used to identify a page of resources. A null value indicates the first page.
func (r AccountsAPIAccountListUsersRequest) PageToken(pageToken string) AccountsAPIAccountListUsersRequest {
	r.pageToken = &pageToken
	return r
}

// A collection of response resources can be transformed by specifying a set of JSON tags to be returned. For a “flat” resource, the tag name is straightforward. If field selection is allowed on non-flat hierarchical resources, the service should implement a qualified naming scheme such as dot-qualification to reference data down the hierarchy. If a resource does not have the specified tag, the tag does not appear in the output resource.  Specify this parameter as a comma-separated list of JSON tag names.
func (r AccountsAPIAccountListUsersRequest) Fields(fields string) AccountsAPIAccountListUsersRequest {
	r.fields = &fields
	return r
}

func (r AccountsAPIAccountListUsersRequest) Execute() (*AccountListUsersResponse, *http.Response, error) {
	return r.ApiService.AccountListUsersExecute(r)
}

/*
AccountListUsers Method for AccountListUsers

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AccountsAPIAccountListUsersRequest
*/
func (a *AccountsAPIService) AccountListUsers(ctx context.Context) AccountsAPIAccountListUsersRequest {
	return AccountsAPIAccountListUsersRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AccountListUsersResponse
func (a *AccountsAPIService) AccountListUsersExecute(r AccountsAPIAccountListUsersRequest) (*AccountListUsersResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *AccountListUsersResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "AccountsAPIService.AccountListUsers")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/accounts/users"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.filter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_filter", r.filter, "")
	}
	if r.orderBy != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_order_by", r.orderBy, "")
	}
	if r.offset != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_offset", r.offset, "")
	}
	if r.limit != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_limit", r.limit, "")
	}
	if r.pageToken != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_token", r.pageToken, "")
	}
	if r.fields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_fields", r.fields, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountsAPICurrentAccountGetRequest struct {
	ctx            context.Context
	ApiService     AccountsAPI
	fields         *string
	includeDeleted *bool
}

// A collection of response resources can be transformed by specifying a set of JSON tags to be returned. For a “flat” resource, the tag name is straightforward. If field selection is allowed on non-flat hierarchical resources, the service should implement a qualified naming scheme such as dot-qualification to reference data down the hierarchy. If a resource does not have the specified tag, the tag does not appear in the output resource.  Specify this parameter as a comma-separated list of JSON tag names.
func (r AccountsAPICurrentAccountGetRequest) Fields(fields string) AccountsAPICurrentAccountGetRequest {
	r.fields = &fields
	return r
}

func (r AccountsAPICurrentAccountGetRequest) IncludeDeleted(includeDeleted bool) AccountsAPICurrentAccountGetRequest {
	r.includeDeleted = &includeDeleted
	return r
}

func (r AccountsAPICurrentAccountGetRequest) Execute() (*AccountGetResponse, *http.Response, error) {
	return r.ApiService.CurrentAccountGetExecute(r)
}

/*
CurrentAccountGet Method for CurrentAccountGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return AccountsAPICurrentAccountGetRequest
*/
func (a *AccountsAPIService) CurrentAccountGet(ctx context.Context) AccountsAPICurrentAccountGetRequest {
	return AccountsAPICurrentAccountGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return AccountGetResponse
func (a *AccountsAPIService) CurrentAccountGetExecute(r AccountsAPICurrentAccountGetRequest) (*AccountGetResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *AccountGetResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "AccountsAPIService.CurrentAccountGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/current_account"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.fields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_fields", r.fields, "")
	}
	if r.includeDeleted != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "include_deleted", r.includeDeleted, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
