/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the ManagedAccountCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedAccountCreateResponse{}

// ManagedAccountCreateResponse struct for ManagedAccountCreateResponse
type ManagedAccountCreateResponse struct {
	Result               *ManagedAccount `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ManagedAccountCreateResponse ManagedAccountCreateResponse

// NewManagedAccountCreateResponse instantiates a new ManagedAccountCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedAccountCreateResponse() *ManagedAccountCreateResponse {
	this := ManagedAccountCreateResponse{}
	return &this
}

// NewManagedAccountCreateResponseWithDefaults instantiates a new ManagedAccountCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedAccountCreateResponseWithDefaults() *ManagedAccountCreateResponse {
	this := ManagedAccountCreateResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ManagedAccountCreateResponse) GetResult() ManagedAccount {
	if o == nil || IsNil(o.Result) {
		var ret ManagedAccount
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccountCreateResponse) GetResultOk() (*ManagedAccount, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ManagedAccountCreateResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ManagedAccount and assigns it to the Result field.
func (o *ManagedAccountCreateResponse) SetResult(v ManagedAccount) {
	o.Result = &v
}

func (o ManagedAccountCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedAccountCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ManagedAccountCreateResponse) UnmarshalJSON(data []byte) (err error) {
	varManagedAccountCreateResponse := _ManagedAccountCreateResponse{}

	err = json.Unmarshal(data, &varManagedAccountCreateResponse)

	if err != nil {
		return err
	}

	*o = ManagedAccountCreateResponse(varManagedAccountCreateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableManagedAccountCreateResponse struct {
	value *ManagedAccountCreateResponse
	isSet bool
}

func (v NullableManagedAccountCreateResponse) Get() *ManagedAccountCreateResponse {
	return v.value
}

func (v *NullableManagedAccountCreateResponse) Set(val *ManagedAccountCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedAccountCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedAccountCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedAccountCreateResponse(val *ManagedAccountCreateResponse) *NullableManagedAccountCreateResponse {
	return &NullableManagedAccountCreateResponse{value: val, isSet: true}
}

func (v NullableManagedAccountCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedAccountCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
