/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the ApikeysCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApikeysCreateRequest{}

// ApikeysCreateRequest struct for ApikeysCreateRequest
type ApikeysCreateRequest struct {
	CompartmentId *string `json:"compartment_id,omitempty"`
	// Expiry timestamp in RFC 3339 / ISO 8601 format (e.g. 2026-01-31T23:59:59Z).
	ExpiresAt *string `json:"expires_at,omitempty"`
	Name      *string `json:"name,omitempty"`
	// The resource identifier.
	UserId               *string `json:"user_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApikeysCreateRequest ApikeysCreateRequest

// NewApikeysCreateRequest instantiates a new ApikeysCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApikeysCreateRequest() *ApikeysCreateRequest {
	this := ApikeysCreateRequest{}
	return &this
}

// NewApikeysCreateRequestWithDefaults instantiates a new ApikeysCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApikeysCreateRequestWithDefaults() *ApikeysCreateRequest {
	this := ApikeysCreateRequest{}
	return &this
}

// GetCompartmentId returns the CompartmentId field value if set, zero value otherwise.
func (o *ApikeysCreateRequest) GetCompartmentId() string {
	if o == nil || IsNil(o.CompartmentId) {
		var ret string
		return ret
	}
	return *o.CompartmentId
}

// GetCompartmentIdOk returns a tuple with the CompartmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApikeysCreateRequest) GetCompartmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.CompartmentId) {
		return nil, false
	}
	return o.CompartmentId, true
}

// HasCompartmentId returns a boolean if a field has been set.
func (o *ApikeysCreateRequest) HasCompartmentId() bool {
	if o != nil && !IsNil(o.CompartmentId) {
		return true
	}

	return false
}

// SetCompartmentId gets a reference to the given string and assigns it to the CompartmentId field.
func (o *ApikeysCreateRequest) SetCompartmentId(v string) {
	o.CompartmentId = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *ApikeysCreateRequest) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApikeysCreateRequest) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ApikeysCreateRequest) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *ApikeysCreateRequest) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApikeysCreateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApikeysCreateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApikeysCreateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApikeysCreateRequest) SetName(v string) {
	o.Name = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ApikeysCreateRequest) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApikeysCreateRequest) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ApikeysCreateRequest) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ApikeysCreateRequest) SetUserId(v string) {
	o.UserId = &v
}

func (o ApikeysCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApikeysCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CompartmentId) {
		toSerialize["compartment_id"] = o.CompartmentId
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApikeysCreateRequest) UnmarshalJSON(data []byte) (err error) {
	varApikeysCreateRequest := _ApikeysCreateRequest{}

	err = json.Unmarshal(data, &varApikeysCreateRequest)

	if err != nil {
		return err
	}

	*o = ApikeysCreateRequest(varApikeysCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "compartment_id")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "name")
		delete(additionalProperties, "user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApikeysCreateRequest struct {
	value *ApikeysCreateRequest
	isSet bool
}

func (v NullableApikeysCreateRequest) Get() *ApikeysCreateRequest {
	return v.value
}

func (v *NullableApikeysCreateRequest) Set(val *ApikeysCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApikeysCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApikeysCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApikeysCreateRequest(val *ApikeysCreateRequest) *NullableApikeysCreateRequest {
	return &NullableApikeysCreateRequest{value: val, isSet: true}
}

func (v NullableApikeysCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApikeysCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
