/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the CompartmentUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompartmentUpdateResponse{}

// CompartmentUpdateResponse struct for CompartmentUpdateResponse
type CompartmentUpdateResponse struct {
	Result               *Compartment `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CompartmentUpdateResponse CompartmentUpdateResponse

// NewCompartmentUpdateResponse instantiates a new CompartmentUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompartmentUpdateResponse() *CompartmentUpdateResponse {
	this := CompartmentUpdateResponse{}
	return &this
}

// NewCompartmentUpdateResponseWithDefaults instantiates a new CompartmentUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompartmentUpdateResponseWithDefaults() *CompartmentUpdateResponse {
	this := CompartmentUpdateResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CompartmentUpdateResponse) GetResult() Compartment {
	if o == nil || IsNil(o.Result) {
		var ret Compartment
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CompartmentUpdateResponse) GetResultOk() (*Compartment, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CompartmentUpdateResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given Compartment and assigns it to the Result field.
func (o *CompartmentUpdateResponse) SetResult(v Compartment) {
	o.Result = &v
}

func (o CompartmentUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompartmentUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CompartmentUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	varCompartmentUpdateResponse := _CompartmentUpdateResponse{}

	err = json.Unmarshal(data, &varCompartmentUpdateResponse)

	if err != nil {
		return err
	}

	*o = CompartmentUpdateResponse(varCompartmentUpdateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCompartmentUpdateResponse struct {
	value *CompartmentUpdateResponse
	isSet bool
}

func (v NullableCompartmentUpdateResponse) Get() *CompartmentUpdateResponse {
	return v.value
}

func (v *NullableCompartmentUpdateResponse) Set(val *CompartmentUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCompartmentUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCompartmentUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompartmentUpdateResponse(val *CompartmentUpdateResponse) *NullableCompartmentUpdateResponse {
	return &NullableCompartmentUpdateResponse{value: val, isSet: true}
}

func (v NullableCompartmentUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompartmentUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
