/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the ApikeysListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApikeysListResponse{}

// ApikeysListResponse struct for ApikeysListResponse
type ApikeysListResponse struct {
	Page                 *ApiPageInfo `json:"page,omitempty"`
	Results              []Apikey     `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApikeysListResponse ApikeysListResponse

// NewApikeysListResponse instantiates a new ApikeysListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApikeysListResponse() *ApikeysListResponse {
	this := ApikeysListResponse{}
	return &this
}

// NewApikeysListResponseWithDefaults instantiates a new ApikeysListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApikeysListResponseWithDefaults() *ApikeysListResponse {
	this := ApikeysListResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ApikeysListResponse) GetPage() ApiPageInfo {
	if o == nil || IsNil(o.Page) {
		var ret ApiPageInfo
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApikeysListResponse) GetPageOk() (*ApiPageInfo, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ApikeysListResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given ApiPageInfo and assigns it to the Page field.
func (o *ApikeysListResponse) SetPage(v ApiPageInfo) {
	o.Page = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *ApikeysListResponse) GetResults() []Apikey {
	if o == nil || IsNil(o.Results) {
		var ret []Apikey
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApikeysListResponse) GetResultsOk() ([]Apikey, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *ApikeysListResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Apikey and assigns it to the Results field.
func (o *ApikeysListResponse) SetResults(v []Apikey) {
	o.Results = v
}

func (o ApikeysListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApikeysListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApikeysListResponse) UnmarshalJSON(data []byte) (err error) {
	varApikeysListResponse := _ApikeysListResponse{}

	err = json.Unmarshal(data, &varApikeysListResponse)

	if err != nil {
		return err
	}

	*o = ApikeysListResponse(varApikeysListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "page")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApikeysListResponse struct {
	value *ApikeysListResponse
	isSet bool
}

func (v NullableApikeysListResponse) Get() *ApikeysListResponse {
	return v.value
}

func (v *NullableApikeysListResponse) Set(val *ApikeysListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApikeysListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApikeysListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApikeysListResponse(val *ApikeysListResponse) *NullableApikeysListResponse {
	return &NullableApikeysListResponse{value: val, isSet: true}
}

func (v NullableApikeysListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApikeysListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
