/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the AccountOrganizationGroupsCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountOrganizationGroupsCreateResponse{}

// AccountOrganizationGroupsCreateResponse struct for AccountOrganizationGroupsCreateResponse
type AccountOrganizationGroupsCreateResponse struct {
	Result               *AccountOrganizationGroup `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AccountOrganizationGroupsCreateResponse AccountOrganizationGroupsCreateResponse

// NewAccountOrganizationGroupsCreateResponse instantiates a new AccountOrganizationGroupsCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountOrganizationGroupsCreateResponse() *AccountOrganizationGroupsCreateResponse {
	this := AccountOrganizationGroupsCreateResponse{}
	return &this
}

// NewAccountOrganizationGroupsCreateResponseWithDefaults instantiates a new AccountOrganizationGroupsCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountOrganizationGroupsCreateResponseWithDefaults() *AccountOrganizationGroupsCreateResponse {
	this := AccountOrganizationGroupsCreateResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *AccountOrganizationGroupsCreateResponse) GetResult() AccountOrganizationGroup {
	if o == nil || IsNil(o.Result) {
		var ret AccountOrganizationGroup
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountOrganizationGroupsCreateResponse) GetResultOk() (*AccountOrganizationGroup, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *AccountOrganizationGroupsCreateResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given AccountOrganizationGroup and assigns it to the Result field.
func (o *AccountOrganizationGroupsCreateResponse) SetResult(v AccountOrganizationGroup) {
	o.Result = &v
}

func (o AccountOrganizationGroupsCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountOrganizationGroupsCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AccountOrganizationGroupsCreateResponse) UnmarshalJSON(data []byte) (err error) {
	varAccountOrganizationGroupsCreateResponse := _AccountOrganizationGroupsCreateResponse{}

	err = json.Unmarshal(data, &varAccountOrganizationGroupsCreateResponse)

	if err != nil {
		return err
	}

	*o = AccountOrganizationGroupsCreateResponse(varAccountOrganizationGroupsCreateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAccountOrganizationGroupsCreateResponse struct {
	value *AccountOrganizationGroupsCreateResponse
	isSet bool
}

func (v NullableAccountOrganizationGroupsCreateResponse) Get() *AccountOrganizationGroupsCreateResponse {
	return v.value
}

func (v *NullableAccountOrganizationGroupsCreateResponse) Set(val *AccountOrganizationGroupsCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountOrganizationGroupsCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountOrganizationGroupsCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountOrganizationGroupsCreateResponse(val *AccountOrganizationGroupsCreateResponse) *NullableAccountOrganizationGroupsCreateResponse {
	return &NullableAccountOrganizationGroupsCreateResponse{value: val, isSet: true}
}

func (v NullableAccountOrganizationGroupsCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountOrganizationGroupsCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
