/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the GroupUpdateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupUpdateResponse{}

// GroupUpdateResponse struct for GroupUpdateResponse
type GroupUpdateResponse struct {
	Result               *Group `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupUpdateResponse GroupUpdateResponse

// NewGroupUpdateResponse instantiates a new GroupUpdateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupUpdateResponse() *GroupUpdateResponse {
	this := GroupUpdateResponse{}
	return &this
}

// NewGroupUpdateResponseWithDefaults instantiates a new GroupUpdateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupUpdateResponseWithDefaults() *GroupUpdateResponse {
	this := GroupUpdateResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GroupUpdateResponse) GetResult() Group {
	if o == nil || IsNil(o.Result) {
		var ret Group
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupUpdateResponse) GetResultOk() (*Group, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GroupUpdateResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given Group and assigns it to the Result field.
func (o *GroupUpdateResponse) SetResult(v Group) {
	o.Result = &v
}

func (o GroupUpdateResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupUpdateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	varGroupUpdateResponse := _GroupUpdateResponse{}

	err = json.Unmarshal(data, &varGroupUpdateResponse)

	if err != nil {
		return err
	}

	*o = GroupUpdateResponse(varGroupUpdateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupUpdateResponse struct {
	value *GroupUpdateResponse
	isSet bool
}

func (v NullableGroupUpdateResponse) Get() *GroupUpdateResponse {
	return v.value
}

func (v *NullableGroupUpdateResponse) Set(val *GroupUpdateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupUpdateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupUpdateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupUpdateResponse(val *GroupUpdateResponse) *NullableGroupUpdateResponse {
	return &NullableGroupUpdateResponse{value: val, isSet: true}
}

func (v NullableGroupUpdateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupUpdateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
