/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the GroupRemoveUserResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupRemoveUserResponse{}

// GroupRemoveUserResponse struct for GroupRemoveUserResponse
type GroupRemoveUserResponse struct {
	Result               *Group `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupRemoveUserResponse GroupRemoveUserResponse

// NewGroupRemoveUserResponse instantiates a new GroupRemoveUserResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupRemoveUserResponse() *GroupRemoveUserResponse {
	this := GroupRemoveUserResponse{}
	return &this
}

// NewGroupRemoveUserResponseWithDefaults instantiates a new GroupRemoveUserResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupRemoveUserResponseWithDefaults() *GroupRemoveUserResponse {
	this := GroupRemoveUserResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *GroupRemoveUserResponse) GetResult() Group {
	if o == nil || IsNil(o.Result) {
		var ret Group
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupRemoveUserResponse) GetResultOk() (*Group, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *GroupRemoveUserResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given Group and assigns it to the Result field.
func (o *GroupRemoveUserResponse) SetResult(v Group) {
	o.Result = &v
}

func (o GroupRemoveUserResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupRemoveUserResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupRemoveUserResponse) UnmarshalJSON(data []byte) (err error) {
	varGroupRemoveUserResponse := _GroupRemoveUserResponse{}

	err = json.Unmarshal(data, &varGroupRemoveUserResponse)

	if err != nil {
		return err
	}

	*o = GroupRemoveUserResponse(varGroupRemoveUserResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupRemoveUserResponse struct {
	value *GroupRemoveUserResponse
	isSet bool
}

func (v NullableGroupRemoveUserResponse) Get() *GroupRemoveUserResponse {
	return v.value
}

func (v *NullableGroupRemoveUserResponse) Set(val *GroupRemoveUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupRemoveUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupRemoveUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupRemoveUserResponse(val *GroupRemoveUserResponse) *NullableGroupRemoveUserResponse {
	return &NullableGroupRemoveUserResponse{value: val, isSet: true}
}

func (v NullableGroupRemoveUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupRemoveUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
