/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
	"time"
)

// checks if the ManagedAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManagedAccount{}

// ManagedAccount struct for ManagedAccount
type ManagedAccount struct {
	// The resource identifier.
	AccountOrganizationGroupId   *string          `json:"account_organization_group_id,omitempty"`
	AccountOrganizationGroupName *string          `json:"account_organization_group_name,omitempty"`
	AccountOrganizationGroupPath *string          `json:"account_organization_group_path,omitempty"`
	AccountType                  *string          `json:"account_type,omitempty"`
	Addresses                    []AccountAddress `json:"addresses,omitempty"`
	AdminUser                    *User            `json:"admin_user,omitempty"`
	// The resource identifier.
	AdminUserId   *string    `json:"admin_user_id,omitempty"`
	AxurAccountId *string    `json:"axur_account_id,omitempty"`
	CompanyDomain *string    `json:"company_domain,omitempty"`
	CompanyNumber *int32     `json:"company_number,omitempty"`
	CreatedAt     *time.Time `json:"created_at,omitempty"`
	CreatedBy     *string    `json:"created_by,omitempty"`
	CspId         *int32     `json:"csp_id,omitempty"`
	DeletedAt     *time.Time `json:"deleted_at,omitempty"`
	Description   *string    `json:"description,omitempty"`
	// The resource identifier.
	Id              *string                           `json:"id,omitempty"`
	IdpAuthnEnabled *bool                             `json:"idp_authn_enabled,omitempty"`
	Labels          map[string]map[string]interface{} `json:"labels,omitempty"`
	ManagementModel *string                           `json:"management_model,omitempty"`
	Name            *string                           `json:"name,omitempty"`
	// The resource identifier.
	ParentAccountId *string `json:"parent_account_id,omitempty"`
	// The resource identifier.
	ParentAccountOrganizationGroupId *string                           `json:"parent_account_organization_group_id,omitempty"`
	PrimaryContact                   *AccountContact                   `json:"primary_contact,omitempty"`
	SfdcAccountId                    *string                           `json:"sfdc_account_id,omitempty"`
	State                            *string                           `json:"state,omitempty"`
	StateChangedAt                   *time.Time                        `json:"state_changed_at,omitempty"`
	StorageId                        *int32                            `json:"storage_id,omitempty"`
	SupportEnabled                   *bool                             `json:"support_enabled,omitempty"`
	Tags                             map[string]map[string]interface{} `json:"tags,omitempty"`
	UpdatedAt                        *time.Time                        `json:"updated_at,omitempty"`
	UserId                           *string                           `json:"user_id,omitempty"`
	AdditionalProperties             map[string]interface{}
}

type _ManagedAccount ManagedAccount

// NewManagedAccount instantiates a new ManagedAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManagedAccount() *ManagedAccount {
	this := ManagedAccount{}
	return &this
}

// NewManagedAccountWithDefaults instantiates a new ManagedAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManagedAccountWithDefaults() *ManagedAccount {
	this := ManagedAccount{}
	return &this
}

// GetAccountOrganizationGroupId returns the AccountOrganizationGroupId field value if set, zero value otherwise.
func (o *ManagedAccount) GetAccountOrganizationGroupId() string {
	if o == nil || IsNil(o.AccountOrganizationGroupId) {
		var ret string
		return ret
	}
	return *o.AccountOrganizationGroupId
}

// GetAccountOrganizationGroupIdOk returns a tuple with the AccountOrganizationGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAccountOrganizationGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountOrganizationGroupId) {
		return nil, false
	}
	return o.AccountOrganizationGroupId, true
}

// HasAccountOrganizationGroupId returns a boolean if a field has been set.
func (o *ManagedAccount) HasAccountOrganizationGroupId() bool {
	if o != nil && !IsNil(o.AccountOrganizationGroupId) {
		return true
	}

	return false
}

// SetAccountOrganizationGroupId gets a reference to the given string and assigns it to the AccountOrganizationGroupId field.
func (o *ManagedAccount) SetAccountOrganizationGroupId(v string) {
	o.AccountOrganizationGroupId = &v
}

// GetAccountOrganizationGroupName returns the AccountOrganizationGroupName field value if set, zero value otherwise.
func (o *ManagedAccount) GetAccountOrganizationGroupName() string {
	if o == nil || IsNil(o.AccountOrganizationGroupName) {
		var ret string
		return ret
	}
	return *o.AccountOrganizationGroupName
}

// GetAccountOrganizationGroupNameOk returns a tuple with the AccountOrganizationGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAccountOrganizationGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountOrganizationGroupName) {
		return nil, false
	}
	return o.AccountOrganizationGroupName, true
}

// HasAccountOrganizationGroupName returns a boolean if a field has been set.
func (o *ManagedAccount) HasAccountOrganizationGroupName() bool {
	if o != nil && !IsNil(o.AccountOrganizationGroupName) {
		return true
	}

	return false
}

// SetAccountOrganizationGroupName gets a reference to the given string and assigns it to the AccountOrganizationGroupName field.
func (o *ManagedAccount) SetAccountOrganizationGroupName(v string) {
	o.AccountOrganizationGroupName = &v
}

// GetAccountOrganizationGroupPath returns the AccountOrganizationGroupPath field value if set, zero value otherwise.
func (o *ManagedAccount) GetAccountOrganizationGroupPath() string {
	if o == nil || IsNil(o.AccountOrganizationGroupPath) {
		var ret string
		return ret
	}
	return *o.AccountOrganizationGroupPath
}

// GetAccountOrganizationGroupPathOk returns a tuple with the AccountOrganizationGroupPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAccountOrganizationGroupPathOk() (*string, bool) {
	if o == nil || IsNil(o.AccountOrganizationGroupPath) {
		return nil, false
	}
	return o.AccountOrganizationGroupPath, true
}

// HasAccountOrganizationGroupPath returns a boolean if a field has been set.
func (o *ManagedAccount) HasAccountOrganizationGroupPath() bool {
	if o != nil && !IsNil(o.AccountOrganizationGroupPath) {
		return true
	}

	return false
}

// SetAccountOrganizationGroupPath gets a reference to the given string and assigns it to the AccountOrganizationGroupPath field.
func (o *ManagedAccount) SetAccountOrganizationGroupPath(v string) {
	o.AccountOrganizationGroupPath = &v
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *ManagedAccount) GetAccountType() string {
	if o == nil || IsNil(o.AccountType) {
		var ret string
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAccountTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *ManagedAccount) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given string and assigns it to the AccountType field.
func (o *ManagedAccount) SetAccountType(v string) {
	o.AccountType = &v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *ManagedAccount) GetAddresses() []AccountAddress {
	if o == nil || IsNil(o.Addresses) {
		var ret []AccountAddress
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAddressesOk() ([]AccountAddress, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *ManagedAccount) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []AccountAddress and assigns it to the Addresses field.
func (o *ManagedAccount) SetAddresses(v []AccountAddress) {
	o.Addresses = v
}

// GetAdminUser returns the AdminUser field value if set, zero value otherwise.
func (o *ManagedAccount) GetAdminUser() User {
	if o == nil || IsNil(o.AdminUser) {
		var ret User
		return ret
	}
	return *o.AdminUser
}

// GetAdminUserOk returns a tuple with the AdminUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAdminUserOk() (*User, bool) {
	if o == nil || IsNil(o.AdminUser) {
		return nil, false
	}
	return o.AdminUser, true
}

// HasAdminUser returns a boolean if a field has been set.
func (o *ManagedAccount) HasAdminUser() bool {
	if o != nil && !IsNil(o.AdminUser) {
		return true
	}

	return false
}

// SetAdminUser gets a reference to the given User and assigns it to the AdminUser field.
func (o *ManagedAccount) SetAdminUser(v User) {
	o.AdminUser = &v
}

// GetAdminUserId returns the AdminUserId field value if set, zero value otherwise.
func (o *ManagedAccount) GetAdminUserId() string {
	if o == nil || IsNil(o.AdminUserId) {
		var ret string
		return ret
	}
	return *o.AdminUserId
}

// GetAdminUserIdOk returns a tuple with the AdminUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAdminUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.AdminUserId) {
		return nil, false
	}
	return o.AdminUserId, true
}

// HasAdminUserId returns a boolean if a field has been set.
func (o *ManagedAccount) HasAdminUserId() bool {
	if o != nil && !IsNil(o.AdminUserId) {
		return true
	}

	return false
}

// SetAdminUserId gets a reference to the given string and assigns it to the AdminUserId field.
func (o *ManagedAccount) SetAdminUserId(v string) {
	o.AdminUserId = &v
}

// GetAxurAccountId returns the AxurAccountId field value if set, zero value otherwise.
func (o *ManagedAccount) GetAxurAccountId() string {
	if o == nil || IsNil(o.AxurAccountId) {
		var ret string
		return ret
	}
	return *o.AxurAccountId
}

// GetAxurAccountIdOk returns a tuple with the AxurAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetAxurAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AxurAccountId) {
		return nil, false
	}
	return o.AxurAccountId, true
}

// HasAxurAccountId returns a boolean if a field has been set.
func (o *ManagedAccount) HasAxurAccountId() bool {
	if o != nil && !IsNil(o.AxurAccountId) {
		return true
	}

	return false
}

// SetAxurAccountId gets a reference to the given string and assigns it to the AxurAccountId field.
func (o *ManagedAccount) SetAxurAccountId(v string) {
	o.AxurAccountId = &v
}

// GetCompanyDomain returns the CompanyDomain field value if set, zero value otherwise.
func (o *ManagedAccount) GetCompanyDomain() string {
	if o == nil || IsNil(o.CompanyDomain) {
		var ret string
		return ret
	}
	return *o.CompanyDomain
}

// GetCompanyDomainOk returns a tuple with the CompanyDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetCompanyDomainOk() (*string, bool) {
	if o == nil || IsNil(o.CompanyDomain) {
		return nil, false
	}
	return o.CompanyDomain, true
}

// HasCompanyDomain returns a boolean if a field has been set.
func (o *ManagedAccount) HasCompanyDomain() bool {
	if o != nil && !IsNil(o.CompanyDomain) {
		return true
	}

	return false
}

// SetCompanyDomain gets a reference to the given string and assigns it to the CompanyDomain field.
func (o *ManagedAccount) SetCompanyDomain(v string) {
	o.CompanyDomain = &v
}

// GetCompanyNumber returns the CompanyNumber field value if set, zero value otherwise.
func (o *ManagedAccount) GetCompanyNumber() int32 {
	if o == nil || IsNil(o.CompanyNumber) {
		var ret int32
		return ret
	}
	return *o.CompanyNumber
}

// GetCompanyNumberOk returns a tuple with the CompanyNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetCompanyNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.CompanyNumber) {
		return nil, false
	}
	return o.CompanyNumber, true
}

// HasCompanyNumber returns a boolean if a field has been set.
func (o *ManagedAccount) HasCompanyNumber() bool {
	if o != nil && !IsNil(o.CompanyNumber) {
		return true
	}

	return false
}

// SetCompanyNumber gets a reference to the given int32 and assigns it to the CompanyNumber field.
func (o *ManagedAccount) SetCompanyNumber(v int32) {
	o.CompanyNumber = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ManagedAccount) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ManagedAccount) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ManagedAccount) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *ManagedAccount) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *ManagedAccount) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *ManagedAccount) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetCspId returns the CspId field value if set, zero value otherwise.
func (o *ManagedAccount) GetCspId() int32 {
	if o == nil || IsNil(o.CspId) {
		var ret int32
		return ret
	}
	return *o.CspId
}

// GetCspIdOk returns a tuple with the CspId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetCspIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CspId) {
		return nil, false
	}
	return o.CspId, true
}

// HasCspId returns a boolean if a field has been set.
func (o *ManagedAccount) HasCspId() bool {
	if o != nil && !IsNil(o.CspId) {
		return true
	}

	return false
}

// SetCspId gets a reference to the given int32 and assigns it to the CspId field.
func (o *ManagedAccount) SetCspId(v int32) {
	o.CspId = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *ManagedAccount) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *ManagedAccount) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *ManagedAccount) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ManagedAccount) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ManagedAccount) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ManagedAccount) SetDescription(v string) {
	o.Description = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ManagedAccount) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ManagedAccount) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ManagedAccount) SetId(v string) {
	o.Id = &v
}

// GetIdpAuthnEnabled returns the IdpAuthnEnabled field value if set, zero value otherwise.
func (o *ManagedAccount) GetIdpAuthnEnabled() bool {
	if o == nil || IsNil(o.IdpAuthnEnabled) {
		var ret bool
		return ret
	}
	return *o.IdpAuthnEnabled
}

// GetIdpAuthnEnabledOk returns a tuple with the IdpAuthnEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetIdpAuthnEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IdpAuthnEnabled) {
		return nil, false
	}
	return o.IdpAuthnEnabled, true
}

// HasIdpAuthnEnabled returns a boolean if a field has been set.
func (o *ManagedAccount) HasIdpAuthnEnabled() bool {
	if o != nil && !IsNil(o.IdpAuthnEnabled) {
		return true
	}

	return false
}

// SetIdpAuthnEnabled gets a reference to the given bool and assigns it to the IdpAuthnEnabled field.
func (o *ManagedAccount) SetIdpAuthnEnabled(v bool) {
	o.IdpAuthnEnabled = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ManagedAccount) GetLabels() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetLabelsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Labels) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ManagedAccount) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]map[string]interface{} and assigns it to the Labels field.
func (o *ManagedAccount) SetLabels(v map[string]map[string]interface{}) {
	o.Labels = v
}

// GetManagementModel returns the ManagementModel field value if set, zero value otherwise.
func (o *ManagedAccount) GetManagementModel() string {
	if o == nil || IsNil(o.ManagementModel) {
		var ret string
		return ret
	}
	return *o.ManagementModel
}

// GetManagementModelOk returns a tuple with the ManagementModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetManagementModelOk() (*string, bool) {
	if o == nil || IsNil(o.ManagementModel) {
		return nil, false
	}
	return o.ManagementModel, true
}

// HasManagementModel returns a boolean if a field has been set.
func (o *ManagedAccount) HasManagementModel() bool {
	if o != nil && !IsNil(o.ManagementModel) {
		return true
	}

	return false
}

// SetManagementModel gets a reference to the given string and assigns it to the ManagementModel field.
func (o *ManagedAccount) SetManagementModel(v string) {
	o.ManagementModel = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ManagedAccount) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ManagedAccount) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ManagedAccount) SetName(v string) {
	o.Name = &v
}

// GetParentAccountId returns the ParentAccountId field value if set, zero value otherwise.
func (o *ManagedAccount) GetParentAccountId() string {
	if o == nil || IsNil(o.ParentAccountId) {
		var ret string
		return ret
	}
	return *o.ParentAccountId
}

// GetParentAccountIdOk returns a tuple with the ParentAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetParentAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentAccountId) {
		return nil, false
	}
	return o.ParentAccountId, true
}

// HasParentAccountId returns a boolean if a field has been set.
func (o *ManagedAccount) HasParentAccountId() bool {
	if o != nil && !IsNil(o.ParentAccountId) {
		return true
	}

	return false
}

// SetParentAccountId gets a reference to the given string and assigns it to the ParentAccountId field.
func (o *ManagedAccount) SetParentAccountId(v string) {
	o.ParentAccountId = &v
}

// GetParentAccountOrganizationGroupId returns the ParentAccountOrganizationGroupId field value if set, zero value otherwise.
func (o *ManagedAccount) GetParentAccountOrganizationGroupId() string {
	if o == nil || IsNil(o.ParentAccountOrganizationGroupId) {
		var ret string
		return ret
	}
	return *o.ParentAccountOrganizationGroupId
}

// GetParentAccountOrganizationGroupIdOk returns a tuple with the ParentAccountOrganizationGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetParentAccountOrganizationGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentAccountOrganizationGroupId) {
		return nil, false
	}
	return o.ParentAccountOrganizationGroupId, true
}

// HasParentAccountOrganizationGroupId returns a boolean if a field has been set.
func (o *ManagedAccount) HasParentAccountOrganizationGroupId() bool {
	if o != nil && !IsNil(o.ParentAccountOrganizationGroupId) {
		return true
	}

	return false
}

// SetParentAccountOrganizationGroupId gets a reference to the given string and assigns it to the ParentAccountOrganizationGroupId field.
func (o *ManagedAccount) SetParentAccountOrganizationGroupId(v string) {
	o.ParentAccountOrganizationGroupId = &v
}

// GetPrimaryContact returns the PrimaryContact field value if set, zero value otherwise.
func (o *ManagedAccount) GetPrimaryContact() AccountContact {
	if o == nil || IsNil(o.PrimaryContact) {
		var ret AccountContact
		return ret
	}
	return *o.PrimaryContact
}

// GetPrimaryContactOk returns a tuple with the PrimaryContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetPrimaryContactOk() (*AccountContact, bool) {
	if o == nil || IsNil(o.PrimaryContact) {
		return nil, false
	}
	return o.PrimaryContact, true
}

// HasPrimaryContact returns a boolean if a field has been set.
func (o *ManagedAccount) HasPrimaryContact() bool {
	if o != nil && !IsNil(o.PrimaryContact) {
		return true
	}

	return false
}

// SetPrimaryContact gets a reference to the given AccountContact and assigns it to the PrimaryContact field.
func (o *ManagedAccount) SetPrimaryContact(v AccountContact) {
	o.PrimaryContact = &v
}

// GetSfdcAccountId returns the SfdcAccountId field value if set, zero value otherwise.
func (o *ManagedAccount) GetSfdcAccountId() string {
	if o == nil || IsNil(o.SfdcAccountId) {
		var ret string
		return ret
	}
	return *o.SfdcAccountId
}

// GetSfdcAccountIdOk returns a tuple with the SfdcAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetSfdcAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.SfdcAccountId) {
		return nil, false
	}
	return o.SfdcAccountId, true
}

// HasSfdcAccountId returns a boolean if a field has been set.
func (o *ManagedAccount) HasSfdcAccountId() bool {
	if o != nil && !IsNil(o.SfdcAccountId) {
		return true
	}

	return false
}

// SetSfdcAccountId gets a reference to the given string and assigns it to the SfdcAccountId field.
func (o *ManagedAccount) SetSfdcAccountId(v string) {
	o.SfdcAccountId = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ManagedAccount) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ManagedAccount) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ManagedAccount) SetState(v string) {
	o.State = &v
}

// GetStateChangedAt returns the StateChangedAt field value if set, zero value otherwise.
func (o *ManagedAccount) GetStateChangedAt() time.Time {
	if o == nil || IsNil(o.StateChangedAt) {
		var ret time.Time
		return ret
	}
	return *o.StateChangedAt
}

// GetStateChangedAtOk returns a tuple with the StateChangedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetStateChangedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StateChangedAt) {
		return nil, false
	}
	return o.StateChangedAt, true
}

// HasStateChangedAt returns a boolean if a field has been set.
func (o *ManagedAccount) HasStateChangedAt() bool {
	if o != nil && !IsNil(o.StateChangedAt) {
		return true
	}

	return false
}

// SetStateChangedAt gets a reference to the given time.Time and assigns it to the StateChangedAt field.
func (o *ManagedAccount) SetStateChangedAt(v time.Time) {
	o.StateChangedAt = &v
}

// GetStorageId returns the StorageId field value if set, zero value otherwise.
func (o *ManagedAccount) GetStorageId() int32 {
	if o == nil || IsNil(o.StorageId) {
		var ret int32
		return ret
	}
	return *o.StorageId
}

// GetStorageIdOk returns a tuple with the StorageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetStorageIdOk() (*int32, bool) {
	if o == nil || IsNil(o.StorageId) {
		return nil, false
	}
	return o.StorageId, true
}

// HasStorageId returns a boolean if a field has been set.
func (o *ManagedAccount) HasStorageId() bool {
	if o != nil && !IsNil(o.StorageId) {
		return true
	}

	return false
}

// SetStorageId gets a reference to the given int32 and assigns it to the StorageId field.
func (o *ManagedAccount) SetStorageId(v int32) {
	o.StorageId = &v
}

// GetSupportEnabled returns the SupportEnabled field value if set, zero value otherwise.
func (o *ManagedAccount) GetSupportEnabled() bool {
	if o == nil || IsNil(o.SupportEnabled) {
		var ret bool
		return ret
	}
	return *o.SupportEnabled
}

// GetSupportEnabledOk returns a tuple with the SupportEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetSupportEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SupportEnabled) {
		return nil, false
	}
	return o.SupportEnabled, true
}

// HasSupportEnabled returns a boolean if a field has been set.
func (o *ManagedAccount) HasSupportEnabled() bool {
	if o != nil && !IsNil(o.SupportEnabled) {
		return true
	}

	return false
}

// SetSupportEnabled gets a reference to the given bool and assigns it to the SupportEnabled field.
func (o *ManagedAccount) SetSupportEnabled(v bool) {
	o.SupportEnabled = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ManagedAccount) GetTags() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetTagsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ManagedAccount) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]map[string]interface{} and assigns it to the Tags field.
func (o *ManagedAccount) SetTags(v map[string]map[string]interface{}) {
	o.Tags = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ManagedAccount) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ManagedAccount) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ManagedAccount) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *ManagedAccount) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManagedAccount) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *ManagedAccount) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *ManagedAccount) SetUserId(v string) {
	o.UserId = &v
}

func (o ManagedAccount) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManagedAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountOrganizationGroupId) {
		toSerialize["account_organization_group_id"] = o.AccountOrganizationGroupId
	}
	if !IsNil(o.AccountOrganizationGroupName) {
		toSerialize["account_organization_group_name"] = o.AccountOrganizationGroupName
	}
	if !IsNil(o.AccountOrganizationGroupPath) {
		toSerialize["account_organization_group_path"] = o.AccountOrganizationGroupPath
	}
	if !IsNil(o.AccountType) {
		toSerialize["account_type"] = o.AccountType
	}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.AdminUser) {
		toSerialize["admin_user"] = o.AdminUser
	}
	if !IsNil(o.AdminUserId) {
		toSerialize["admin_user_id"] = o.AdminUserId
	}
	if !IsNil(o.AxurAccountId) {
		toSerialize["axur_account_id"] = o.AxurAccountId
	}
	if !IsNil(o.CompanyDomain) {
		toSerialize["company_domain"] = o.CompanyDomain
	}
	if !IsNil(o.CompanyNumber) {
		toSerialize["company_number"] = o.CompanyNumber
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.CspId) {
		toSerialize["csp_id"] = o.CspId
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IdpAuthnEnabled) {
		toSerialize["idp_authn_enabled"] = o.IdpAuthnEnabled
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.ManagementModel) {
		toSerialize["management_model"] = o.ManagementModel
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ParentAccountId) {
		toSerialize["parent_account_id"] = o.ParentAccountId
	}
	if !IsNil(o.ParentAccountOrganizationGroupId) {
		toSerialize["parent_account_organization_group_id"] = o.ParentAccountOrganizationGroupId
	}
	if !IsNil(o.PrimaryContact) {
		toSerialize["primary_contact"] = o.PrimaryContact
	}
	if !IsNil(o.SfdcAccountId) {
		toSerialize["sfdc_account_id"] = o.SfdcAccountId
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.StateChangedAt) {
		toSerialize["state_changed_at"] = o.StateChangedAt
	}
	if !IsNil(o.StorageId) {
		toSerialize["storage_id"] = o.StorageId
	}
	if !IsNil(o.SupportEnabled) {
		toSerialize["support_enabled"] = o.SupportEnabled
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ManagedAccount) UnmarshalJSON(data []byte) (err error) {
	varManagedAccount := _ManagedAccount{}

	err = json.Unmarshal(data, &varManagedAccount)

	if err != nil {
		return err
	}

	*o = ManagedAccount(varManagedAccount)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_organization_group_id")
		delete(additionalProperties, "account_organization_group_name")
		delete(additionalProperties, "account_organization_group_path")
		delete(additionalProperties, "account_type")
		delete(additionalProperties, "addresses")
		delete(additionalProperties, "admin_user")
		delete(additionalProperties, "admin_user_id")
		delete(additionalProperties, "axur_account_id")
		delete(additionalProperties, "company_domain")
		delete(additionalProperties, "company_number")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "created_by")
		delete(additionalProperties, "csp_id")
		delete(additionalProperties, "deleted_at")
		delete(additionalProperties, "description")
		delete(additionalProperties, "id")
		delete(additionalProperties, "idp_authn_enabled")
		delete(additionalProperties, "labels")
		delete(additionalProperties, "management_model")
		delete(additionalProperties, "name")
		delete(additionalProperties, "parent_account_id")
		delete(additionalProperties, "parent_account_organization_group_id")
		delete(additionalProperties, "primary_contact")
		delete(additionalProperties, "sfdc_account_id")
		delete(additionalProperties, "state")
		delete(additionalProperties, "state_changed_at")
		delete(additionalProperties, "storage_id")
		delete(additionalProperties, "support_enabled")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "user_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableManagedAccount struct {
	value *ManagedAccount
	isSet bool
}

func (v NullableManagedAccount) Get() *ManagedAccount {
	return v.value
}

func (v *NullableManagedAccount) Set(val *ManagedAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableManagedAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableManagedAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManagedAccount(val *ManagedAccount) *NullableManagedAccount {
	return &NullableManagedAccount{value: val, isSet: true}
}

func (v NullableManagedAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManagedAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
