/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the UserGetResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserGetResponse{}

// UserGetResponse struct for UserGetResponse
type UserGetResponse struct {
	Result               *User `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserGetResponse UserGetResponse

// NewUserGetResponse instantiates a new UserGetResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserGetResponse() *UserGetResponse {
	this := UserGetResponse{}
	return &this
}

// NewUserGetResponseWithDefaults instantiates a new UserGetResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserGetResponseWithDefaults() *UserGetResponse {
	this := UserGetResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *UserGetResponse) GetResult() User {
	if o == nil || IsNil(o.Result) {
		var ret User
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserGetResponse) GetResultOk() (*User, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *UserGetResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given User and assigns it to the Result field.
func (o *UserGetResponse) SetResult(v User) {
	o.Result = &v
}

func (o UserGetResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserGetResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserGetResponse) UnmarshalJSON(data []byte) (err error) {
	varUserGetResponse := _UserGetResponse{}

	err = json.Unmarshal(data, &varUserGetResponse)

	if err != nil {
		return err
	}

	*o = UserGetResponse(varUserGetResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserGetResponse struct {
	value *UserGetResponse
	isSet bool
}

func (v NullableUserGetResponse) Get() *UserGetResponse {
	return v.value
}

func (v *NullableUserGetResponse) Set(val *UserGetResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserGetResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserGetResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserGetResponse(val *UserGetResponse) *NullableUserGetResponse {
	return &NullableUserGetResponse{value: val, isSet: true}
}

func (v NullableUserGetResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserGetResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
