/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the UserCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserCreateRequest{}

// UserCreateRequest struct for UserCreateRequest
type UserCreateRequest struct {
	// The resource identifier.
	AccountId *string `json:"account_id,omitempty"`
	// ISO 3166-1 alpha-2 country code (required for interactive users).
	Country *string `json:"country,omitempty"`
	// The email address of the user.
	Email *string `json:"email,omitempty"`
	// The first name of the user.
	FirstName *string `json:"first_name,omitempty"`
	// The resource identifier.
	GroupIds []string `json:"group_ids,omitempty"`
	// The resource identifier.
	Id *string `json:"id,omitempty"`
	// Job title (required for interactive users).
	JobTitle *string `json:"job_title,omitempty"`
	// The last name of the user.
	LastName *string `json:"last_name,omitempty"`
	// Marketing communications opt-in preference (required for interactive users).
	MarketingOptIn *bool `json:"marketing_opt_in,omitempty"`
	// The name of the user.
	Name *string `json:"name,omitempty"`
	// ISO 3166-2 subdivision code, or free-text for countries without subdivisions (required for interactive users).
	StateRegion *string `json:"state_region,omitempty"`
	// The type of the user (HostAppUser/ATEP/local/service/interactive).
	Type                 *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UserCreateRequest UserCreateRequest

// NewUserCreateRequest instantiates a new UserCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserCreateRequest() *UserCreateRequest {
	this := UserCreateRequest{}
	return &this
}

// NewUserCreateRequestWithDefaults instantiates a new UserCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserCreateRequestWithDefaults() *UserCreateRequest {
	this := UserCreateRequest{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *UserCreateRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *UserCreateRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *UserCreateRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *UserCreateRequest) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *UserCreateRequest) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *UserCreateRequest) SetCountry(v string) {
	o.Country = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserCreateRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserCreateRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserCreateRequest) SetEmail(v string) {
	o.Email = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserCreateRequest) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserCreateRequest) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserCreateRequest) SetFirstName(v string) {
	o.FirstName = &v
}

// GetGroupIds returns the GroupIds field value if set, zero value otherwise.
func (o *UserCreateRequest) GetGroupIds() []string {
	if o == nil || IsNil(o.GroupIds) {
		var ret []string
		return ret
	}
	return o.GroupIds
}

// GetGroupIdsOk returns a tuple with the GroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupIds) {
		return nil, false
	}
	return o.GroupIds, true
}

// HasGroupIds returns a boolean if a field has been set.
func (o *UserCreateRequest) HasGroupIds() bool {
	if o != nil && !IsNil(o.GroupIds) {
		return true
	}

	return false
}

// SetGroupIds gets a reference to the given []string and assigns it to the GroupIds field.
func (o *UserCreateRequest) SetGroupIds(v []string) {
	o.GroupIds = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserCreateRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserCreateRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserCreateRequest) SetId(v string) {
	o.Id = &v
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *UserCreateRequest) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *UserCreateRequest) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *UserCreateRequest) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserCreateRequest) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserCreateRequest) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserCreateRequest) SetLastName(v string) {
	o.LastName = &v
}

// GetMarketingOptIn returns the MarketingOptIn field value if set, zero value otherwise.
func (o *UserCreateRequest) GetMarketingOptIn() bool {
	if o == nil || IsNil(o.MarketingOptIn) {
		var ret bool
		return ret
	}
	return *o.MarketingOptIn
}

// GetMarketingOptInOk returns a tuple with the MarketingOptIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetMarketingOptInOk() (*bool, bool) {
	if o == nil || IsNil(o.MarketingOptIn) {
		return nil, false
	}
	return o.MarketingOptIn, true
}

// HasMarketingOptIn returns a boolean if a field has been set.
func (o *UserCreateRequest) HasMarketingOptIn() bool {
	if o != nil && !IsNil(o.MarketingOptIn) {
		return true
	}

	return false
}

// SetMarketingOptIn gets a reference to the given bool and assigns it to the MarketingOptIn field.
func (o *UserCreateRequest) SetMarketingOptIn(v bool) {
	o.MarketingOptIn = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserCreateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserCreateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserCreateRequest) SetName(v string) {
	o.Name = &v
}

// GetStateRegion returns the StateRegion field value if set, zero value otherwise.
func (o *UserCreateRequest) GetStateRegion() string {
	if o == nil || IsNil(o.StateRegion) {
		var ret string
		return ret
	}
	return *o.StateRegion
}

// GetStateRegionOk returns a tuple with the StateRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetStateRegionOk() (*string, bool) {
	if o == nil || IsNil(o.StateRegion) {
		return nil, false
	}
	return o.StateRegion, true
}

// HasStateRegion returns a boolean if a field has been set.
func (o *UserCreateRequest) HasStateRegion() bool {
	if o != nil && !IsNil(o.StateRegion) {
		return true
	}

	return false
}

// SetStateRegion gets a reference to the given string and assigns it to the StateRegion field.
func (o *UserCreateRequest) SetStateRegion(v string) {
	o.StateRegion = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UserCreateRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserCreateRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UserCreateRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UserCreateRequest) SetType(v string) {
	o.Type = &v
}

func (o UserCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.GroupIds) {
		toSerialize["group_ids"] = o.GroupIds
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.JobTitle) {
		toSerialize["job_title"] = o.JobTitle
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.MarketingOptIn) {
		toSerialize["marketing_opt_in"] = o.MarketingOptIn
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.StateRegion) {
		toSerialize["state_region"] = o.StateRegion
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserCreateRequest) UnmarshalJSON(data []byte) (err error) {
	varUserCreateRequest := _UserCreateRequest{}

	err = json.Unmarshal(data, &varUserCreateRequest)

	if err != nil {
		return err
	}

	*o = UserCreateRequest(varUserCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "country")
		delete(additionalProperties, "email")
		delete(additionalProperties, "first_name")
		delete(additionalProperties, "group_ids")
		delete(additionalProperties, "id")
		delete(additionalProperties, "job_title")
		delete(additionalProperties, "last_name")
		delete(additionalProperties, "marketing_opt_in")
		delete(additionalProperties, "name")
		delete(additionalProperties, "state_region")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserCreateRequest struct {
	value *UserCreateRequest
	isSet bool
}

func (v NullableUserCreateRequest) Get() *UserCreateRequest {
	return v.value
}

func (v *NullableUserCreateRequest) Set(val *UserCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUserCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUserCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserCreateRequest(val *UserCreateRequest) *NullableUserCreateRequest {
	return &NullableUserCreateRequest{value: val, isSet: true}
}

func (v NullableUserCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
