/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
)

// checks if the GroupListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupListResponse{}

// GroupListResponse struct for GroupListResponse
type GroupListResponse struct {
	Page                 *ApiPageInfo `json:"page,omitempty"`
	Results              []Group      `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GroupListResponse GroupListResponse

// NewGroupListResponse instantiates a new GroupListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupListResponse() *GroupListResponse {
	this := GroupListResponse{}
	return &this
}

// NewGroupListResponseWithDefaults instantiates a new GroupListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupListResponseWithDefaults() *GroupListResponse {
	this := GroupListResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GroupListResponse) GetPage() ApiPageInfo {
	if o == nil || IsNil(o.Page) {
		var ret ApiPageInfo
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupListResponse) GetPageOk() (*ApiPageInfo, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GroupListResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given ApiPageInfo and assigns it to the Page field.
func (o *GroupListResponse) SetPage(v ApiPageInfo) {
	o.Page = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GroupListResponse) GetResults() []Group {
	if o == nil || IsNil(o.Results) {
		var ret []Group
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroupListResponse) GetResultsOk() ([]Group, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GroupListResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Group and assigns it to the Results field.
func (o *GroupListResponse) SetResults(v []Group) {
	o.Results = v
}

func (o GroupListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupListResponse) UnmarshalJSON(data []byte) (err error) {
	varGroupListResponse := _GroupListResponse{}

	err = json.Unmarshal(data, &varGroupListResponse)

	if err != nil {
		return err
	}

	*o = GroupListResponse(varGroupListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "page")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupListResponse struct {
	value *GroupListResponse
	isSet bool
}

func (v NullableGroupListResponse) Get() *GroupListResponse {
	return v.value
}

func (v *NullableGroupListResponse) Set(val *GroupListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupListResponse(val *GroupListResponse) *NullableGroupListResponse {
	return &NullableGroupListResponse{value: val, isSet: true}
}

func (v NullableGroupListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
