/*
Identity API

The purpose of the Athena Identity Service is to manage users and groups. Following endpoints require \"user manage\" permission:  - /v2/users   - /v2/groups Following endpoints require administrator role (admin, act_admin, ib-access-control-admin or ib-ddi-admin):  - POST /v2/compartments  - PUT /v2/compartments  - PATCH /v2/compartments

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package identity

import (
	"encoding/json"
	"time"
)

// checks if the UserInIdentityV2Group type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInIdentityV2Group{}

// UserInIdentityV2Group struct for UserInIdentityV2Group
type UserInIdentityV2Group struct {
	Account      *AccountInIdentityV2User `json:"account,omitempty"`
	AccountCspId *int32                   `json:"account_csp_id,omitempty"`
	// The resource identifier.
	AccountId          *string    `json:"account_id,omitempty"`
	AccountInfobloxId  *string    `json:"account_infoblox_id,omitempty"`
	AgreementsAccepted *bool      `json:"agreements_accepted,omitempty"`
	ApiKey             *string    `json:"api_key,omitempty"`
	ApiKeys            []string   `json:"api_keys,omitempty"`
	Approved           *bool      `json:"approved,omitempty"`
	Authenticator      *string    `json:"authenticator,omitempty"`
	ConfirmToken       *string    `json:"confirm_token,omitempty"`
	ConfirmationSentAt *time.Time `json:"confirmation_sent_at,omitempty"`
	ConfirmedAt        *time.Time `json:"confirmed_at,omitempty"`
	Country            *string    `json:"country,omitempty"`
	CreatedAt          *time.Time `json:"created_at,omitempty"`
	CspId              *int32     `json:"csp_id,omitempty"`
	DeletedAt          *time.Time `json:"deleted_at,omitempty"`
	DeletedBy          *string    `json:"deleted_by,omitempty"`
	Email              *string    `json:"email,omitempty"`
	FailedAttempts     *int32     `json:"failed_attempts,omitempty"`
	FirstName          *string    `json:"first_name,omitempty"`
	// The resource identifier.
	GroupIds []string `json:"group_ids,omitempty"`
	// The resource identifier.
	Id                        *string                           `json:"id,omitempty"`
	JobTitle                  *string                           `json:"job_title,omitempty"`
	LastLogin                 *time.Time                        `json:"last_login,omitempty"`
	LastName                  *string                           `json:"last_name,omitempty"`
	LastValidatedAt           *time.Time                        `json:"last_validated_at,omitempty"`
	LockedAt                  *time.Time                        `json:"locked_at,omitempty"`
	MarketingOptIn            *bool                             `json:"marketing_opt_in,omitempty"`
	Name                      *string                           `json:"name,omitempty"`
	NextRevalidationDueAt     *time.Time                        `json:"next_revalidation_due_at,omitempty"`
	Origin                    *string                           `json:"origin,omitempty"`
	PasswordHash              *string                           `json:"password_hash,omitempty"`
	PhoneNumber               *string                           `json:"phone_number,omitempty"`
	ProfileValidationRequired *bool                             `json:"profile_validation_required,omitempty"`
	ResetPasswordSentAt       *time.Time                        `json:"reset_password_sent_at,omitempty"`
	ResetPasswordToken        *string                           `json:"reset_password_token,omitempty"`
	SignInCount               *int32                            `json:"sign_in_count,omitempty"`
	State                     *string                           `json:"state,omitempty"`
	StateChangedAt            *time.Time                        `json:"state_changed_at,omitempty"`
	StateRegion               *string                           `json:"state_region,omitempty"`
	Tags                      map[string]map[string]interface{} `json:"tags,omitempty"`
	Timezone                  *string                           `json:"timezone,omitempty"`
	Type                      *string                           `json:"type,omitempty"`
	UnlockToken               *string                           `json:"unlock_token,omitempty"`
	UpdatedAt                 *time.Time                        `json:"updated_at,omitempty"`
	AdditionalProperties      map[string]interface{}
}

type _UserInIdentityV2Group UserInIdentityV2Group

// NewUserInIdentityV2Group instantiates a new UserInIdentityV2Group object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInIdentityV2Group() *UserInIdentityV2Group {
	this := UserInIdentityV2Group{}
	return &this
}

// NewUserInIdentityV2GroupWithDefaults instantiates a new UserInIdentityV2Group object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInIdentityV2GroupWithDefaults() *UserInIdentityV2Group {
	this := UserInIdentityV2Group{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetAccount() AccountInIdentityV2User {
	if o == nil || IsNil(o.Account) {
		var ret AccountInIdentityV2User
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetAccountOk() (*AccountInIdentityV2User, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountInIdentityV2User and assigns it to the Account field.
func (o *UserInIdentityV2Group) SetAccount(v AccountInIdentityV2User) {
	o.Account = &v
}

// GetAccountCspId returns the AccountCspId field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetAccountCspId() int32 {
	if o == nil || IsNil(o.AccountCspId) {
		var ret int32
		return ret
	}
	return *o.AccountCspId
}

// GetAccountCspIdOk returns a tuple with the AccountCspId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetAccountCspIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountCspId) {
		return nil, false
	}
	return o.AccountCspId, true
}

// HasAccountCspId returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasAccountCspId() bool {
	if o != nil && !IsNil(o.AccountCspId) {
		return true
	}

	return false
}

// SetAccountCspId gets a reference to the given int32 and assigns it to the AccountCspId field.
func (o *UserInIdentityV2Group) SetAccountCspId(v int32) {
	o.AccountCspId = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *UserInIdentityV2Group) SetAccountId(v string) {
	o.AccountId = &v
}

// GetAccountInfobloxId returns the AccountInfobloxId field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetAccountInfobloxId() string {
	if o == nil || IsNil(o.AccountInfobloxId) {
		var ret string
		return ret
	}
	return *o.AccountInfobloxId
}

// GetAccountInfobloxIdOk returns a tuple with the AccountInfobloxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetAccountInfobloxIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountInfobloxId) {
		return nil, false
	}
	return o.AccountInfobloxId, true
}

// HasAccountInfobloxId returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasAccountInfobloxId() bool {
	if o != nil && !IsNil(o.AccountInfobloxId) {
		return true
	}

	return false
}

// SetAccountInfobloxId gets a reference to the given string and assigns it to the AccountInfobloxId field.
func (o *UserInIdentityV2Group) SetAccountInfobloxId(v string) {
	o.AccountInfobloxId = &v
}

// GetAgreementsAccepted returns the AgreementsAccepted field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetAgreementsAccepted() bool {
	if o == nil || IsNil(o.AgreementsAccepted) {
		var ret bool
		return ret
	}
	return *o.AgreementsAccepted
}

// GetAgreementsAcceptedOk returns a tuple with the AgreementsAccepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetAgreementsAcceptedOk() (*bool, bool) {
	if o == nil || IsNil(o.AgreementsAccepted) {
		return nil, false
	}
	return o.AgreementsAccepted, true
}

// HasAgreementsAccepted returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasAgreementsAccepted() bool {
	if o != nil && !IsNil(o.AgreementsAccepted) {
		return true
	}

	return false
}

// SetAgreementsAccepted gets a reference to the given bool and assigns it to the AgreementsAccepted field.
func (o *UserInIdentityV2Group) SetAgreementsAccepted(v bool) {
	o.AgreementsAccepted = &v
}

// GetApiKey returns the ApiKey field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetApiKey() string {
	if o == nil || IsNil(o.ApiKey) {
		var ret string
		return ret
	}
	return *o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetApiKeyOk() (*string, bool) {
	if o == nil || IsNil(o.ApiKey) {
		return nil, false
	}
	return o.ApiKey, true
}

// HasApiKey returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasApiKey() bool {
	if o != nil && !IsNil(o.ApiKey) {
		return true
	}

	return false
}

// SetApiKey gets a reference to the given string and assigns it to the ApiKey field.
func (o *UserInIdentityV2Group) SetApiKey(v string) {
	o.ApiKey = &v
}

// GetApiKeys returns the ApiKeys field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetApiKeys() []string {
	if o == nil || IsNil(o.ApiKeys) {
		var ret []string
		return ret
	}
	return o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetApiKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.ApiKeys) {
		return nil, false
	}
	return o.ApiKeys, true
}

// HasApiKeys returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasApiKeys() bool {
	if o != nil && !IsNil(o.ApiKeys) {
		return true
	}

	return false
}

// SetApiKeys gets a reference to the given []string and assigns it to the ApiKeys field.
func (o *UserInIdentityV2Group) SetApiKeys(v []string) {
	o.ApiKeys = v
}

// GetApproved returns the Approved field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetApproved() bool {
	if o == nil || IsNil(o.Approved) {
		var ret bool
		return ret
	}
	return *o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetApprovedOk() (*bool, bool) {
	if o == nil || IsNil(o.Approved) {
		return nil, false
	}
	return o.Approved, true
}

// HasApproved returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasApproved() bool {
	if o != nil && !IsNil(o.Approved) {
		return true
	}

	return false
}

// SetApproved gets a reference to the given bool and assigns it to the Approved field.
func (o *UserInIdentityV2Group) SetApproved(v bool) {
	o.Approved = &v
}

// GetAuthenticator returns the Authenticator field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetAuthenticator() string {
	if o == nil || IsNil(o.Authenticator) {
		var ret string
		return ret
	}
	return *o.Authenticator
}

// GetAuthenticatorOk returns a tuple with the Authenticator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetAuthenticatorOk() (*string, bool) {
	if o == nil || IsNil(o.Authenticator) {
		return nil, false
	}
	return o.Authenticator, true
}

// HasAuthenticator returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasAuthenticator() bool {
	if o != nil && !IsNil(o.Authenticator) {
		return true
	}

	return false
}

// SetAuthenticator gets a reference to the given string and assigns it to the Authenticator field.
func (o *UserInIdentityV2Group) SetAuthenticator(v string) {
	o.Authenticator = &v
}

// GetConfirmToken returns the ConfirmToken field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetConfirmToken() string {
	if o == nil || IsNil(o.ConfirmToken) {
		var ret string
		return ret
	}
	return *o.ConfirmToken
}

// GetConfirmTokenOk returns a tuple with the ConfirmToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetConfirmTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ConfirmToken) {
		return nil, false
	}
	return o.ConfirmToken, true
}

// HasConfirmToken returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasConfirmToken() bool {
	if o != nil && !IsNil(o.ConfirmToken) {
		return true
	}

	return false
}

// SetConfirmToken gets a reference to the given string and assigns it to the ConfirmToken field.
func (o *UserInIdentityV2Group) SetConfirmToken(v string) {
	o.ConfirmToken = &v
}

// GetConfirmationSentAt returns the ConfirmationSentAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetConfirmationSentAt() time.Time {
	if o == nil || IsNil(o.ConfirmationSentAt) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmationSentAt
}

// GetConfirmationSentAtOk returns a tuple with the ConfirmationSentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetConfirmationSentAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ConfirmationSentAt) {
		return nil, false
	}
	return o.ConfirmationSentAt, true
}

// HasConfirmationSentAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasConfirmationSentAt() bool {
	if o != nil && !IsNil(o.ConfirmationSentAt) {
		return true
	}

	return false
}

// SetConfirmationSentAt gets a reference to the given time.Time and assigns it to the ConfirmationSentAt field.
func (o *UserInIdentityV2Group) SetConfirmationSentAt(v time.Time) {
	o.ConfirmationSentAt = &v
}

// GetConfirmedAt returns the ConfirmedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetConfirmedAt() time.Time {
	if o == nil || IsNil(o.ConfirmedAt) {
		var ret time.Time
		return ret
	}
	return *o.ConfirmedAt
}

// GetConfirmedAtOk returns a tuple with the ConfirmedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetConfirmedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ConfirmedAt) {
		return nil, false
	}
	return o.ConfirmedAt, true
}

// HasConfirmedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasConfirmedAt() bool {
	if o != nil && !IsNil(o.ConfirmedAt) {
		return true
	}

	return false
}

// SetConfirmedAt gets a reference to the given time.Time and assigns it to the ConfirmedAt field.
func (o *UserInIdentityV2Group) SetConfirmedAt(v time.Time) {
	o.ConfirmedAt = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *UserInIdentityV2Group) SetCountry(v string) {
	o.Country = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UserInIdentityV2Group) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetCspId returns the CspId field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetCspId() int32 {
	if o == nil || IsNil(o.CspId) {
		var ret int32
		return ret
	}
	return *o.CspId
}

// GetCspIdOk returns a tuple with the CspId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetCspIdOk() (*int32, bool) {
	if o == nil || IsNil(o.CspId) {
		return nil, false
	}
	return o.CspId, true
}

// HasCspId returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasCspId() bool {
	if o != nil && !IsNil(o.CspId) {
		return true
	}

	return false
}

// SetCspId gets a reference to the given int32 and assigns it to the CspId field.
func (o *UserInIdentityV2Group) SetCspId(v int32) {
	o.CspId = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given time.Time and assigns it to the DeletedAt field.
func (o *UserInIdentityV2Group) SetDeletedAt(v time.Time) {
	o.DeletedAt = &v
}

// GetDeletedBy returns the DeletedBy field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetDeletedBy() string {
	if o == nil || IsNil(o.DeletedBy) {
		var ret string
		return ret
	}
	return *o.DeletedBy
}

// GetDeletedByOk returns a tuple with the DeletedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetDeletedByOk() (*string, bool) {
	if o == nil || IsNil(o.DeletedBy) {
		return nil, false
	}
	return o.DeletedBy, true
}

// HasDeletedBy returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasDeletedBy() bool {
	if o != nil && !IsNil(o.DeletedBy) {
		return true
	}

	return false
}

// SetDeletedBy gets a reference to the given string and assigns it to the DeletedBy field.
func (o *UserInIdentityV2Group) SetDeletedBy(v string) {
	o.DeletedBy = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UserInIdentityV2Group) SetEmail(v string) {
	o.Email = &v
}

// GetFailedAttempts returns the FailedAttempts field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetFailedAttempts() int32 {
	if o == nil || IsNil(o.FailedAttempts) {
		var ret int32
		return ret
	}
	return *o.FailedAttempts
}

// GetFailedAttemptsOk returns a tuple with the FailedAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetFailedAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.FailedAttempts) {
		return nil, false
	}
	return o.FailedAttempts, true
}

// HasFailedAttempts returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasFailedAttempts() bool {
	if o != nil && !IsNil(o.FailedAttempts) {
		return true
	}

	return false
}

// SetFailedAttempts gets a reference to the given int32 and assigns it to the FailedAttempts field.
func (o *UserInIdentityV2Group) SetFailedAttempts(v int32) {
	o.FailedAttempts = &v
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *UserInIdentityV2Group) SetFirstName(v string) {
	o.FirstName = &v
}

// GetGroupIds returns the GroupIds field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetGroupIds() []string {
	if o == nil || IsNil(o.GroupIds) {
		var ret []string
		return ret
	}
	return o.GroupIds
}

// GetGroupIdsOk returns a tuple with the GroupIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetGroupIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.GroupIds) {
		return nil, false
	}
	return o.GroupIds, true
}

// HasGroupIds returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasGroupIds() bool {
	if o != nil && !IsNil(o.GroupIds) {
		return true
	}

	return false
}

// SetGroupIds gets a reference to the given []string and assigns it to the GroupIds field.
func (o *UserInIdentityV2Group) SetGroupIds(v []string) {
	o.GroupIds = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserInIdentityV2Group) SetId(v string) {
	o.Id = &v
}

// GetJobTitle returns the JobTitle field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetJobTitle() string {
	if o == nil || IsNil(o.JobTitle) {
		var ret string
		return ret
	}
	return *o.JobTitle
}

// GetJobTitleOk returns a tuple with the JobTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetJobTitleOk() (*string, bool) {
	if o == nil || IsNil(o.JobTitle) {
		return nil, false
	}
	return o.JobTitle, true
}

// HasJobTitle returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasJobTitle() bool {
	if o != nil && !IsNil(o.JobTitle) {
		return true
	}

	return false
}

// SetJobTitle gets a reference to the given string and assigns it to the JobTitle field.
func (o *UserInIdentityV2Group) SetJobTitle(v string) {
	o.JobTitle = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetLastLogin() time.Time {
	if o == nil || IsNil(o.LastLogin) {
		var ret time.Time
		return ret
	}
	return *o.LastLogin
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetLastLoginOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastLogin) {
		return nil, false
	}
	return o.LastLogin, true
}

// HasLastLogin returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasLastLogin() bool {
	if o != nil && !IsNil(o.LastLogin) {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given time.Time and assigns it to the LastLogin field.
func (o *UserInIdentityV2Group) SetLastLogin(v time.Time) {
	o.LastLogin = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *UserInIdentityV2Group) SetLastName(v string) {
	o.LastName = &v
}

// GetLastValidatedAt returns the LastValidatedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetLastValidatedAt() time.Time {
	if o == nil || IsNil(o.LastValidatedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastValidatedAt
}

// GetLastValidatedAtOk returns a tuple with the LastValidatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetLastValidatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastValidatedAt) {
		return nil, false
	}
	return o.LastValidatedAt, true
}

// HasLastValidatedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasLastValidatedAt() bool {
	if o != nil && !IsNil(o.LastValidatedAt) {
		return true
	}

	return false
}

// SetLastValidatedAt gets a reference to the given time.Time and assigns it to the LastValidatedAt field.
func (o *UserInIdentityV2Group) SetLastValidatedAt(v time.Time) {
	o.LastValidatedAt = &v
}

// GetLockedAt returns the LockedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetLockedAt() time.Time {
	if o == nil || IsNil(o.LockedAt) {
		var ret time.Time
		return ret
	}
	return *o.LockedAt
}

// GetLockedAtOk returns a tuple with the LockedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetLockedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LockedAt) {
		return nil, false
	}
	return o.LockedAt, true
}

// HasLockedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasLockedAt() bool {
	if o != nil && !IsNil(o.LockedAt) {
		return true
	}

	return false
}

// SetLockedAt gets a reference to the given time.Time and assigns it to the LockedAt field.
func (o *UserInIdentityV2Group) SetLockedAt(v time.Time) {
	o.LockedAt = &v
}

// GetMarketingOptIn returns the MarketingOptIn field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetMarketingOptIn() bool {
	if o == nil || IsNil(o.MarketingOptIn) {
		var ret bool
		return ret
	}
	return *o.MarketingOptIn
}

// GetMarketingOptInOk returns a tuple with the MarketingOptIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetMarketingOptInOk() (*bool, bool) {
	if o == nil || IsNil(o.MarketingOptIn) {
		return nil, false
	}
	return o.MarketingOptIn, true
}

// HasMarketingOptIn returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasMarketingOptIn() bool {
	if o != nil && !IsNil(o.MarketingOptIn) {
		return true
	}

	return false
}

// SetMarketingOptIn gets a reference to the given bool and assigns it to the MarketingOptIn field.
func (o *UserInIdentityV2Group) SetMarketingOptIn(v bool) {
	o.MarketingOptIn = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UserInIdentityV2Group) SetName(v string) {
	o.Name = &v
}

// GetNextRevalidationDueAt returns the NextRevalidationDueAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetNextRevalidationDueAt() time.Time {
	if o == nil || IsNil(o.NextRevalidationDueAt) {
		var ret time.Time
		return ret
	}
	return *o.NextRevalidationDueAt
}

// GetNextRevalidationDueAtOk returns a tuple with the NextRevalidationDueAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetNextRevalidationDueAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.NextRevalidationDueAt) {
		return nil, false
	}
	return o.NextRevalidationDueAt, true
}

// HasNextRevalidationDueAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasNextRevalidationDueAt() bool {
	if o != nil && !IsNil(o.NextRevalidationDueAt) {
		return true
	}

	return false
}

// SetNextRevalidationDueAt gets a reference to the given time.Time and assigns it to the NextRevalidationDueAt field.
func (o *UserInIdentityV2Group) SetNextRevalidationDueAt(v time.Time) {
	o.NextRevalidationDueAt = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *UserInIdentityV2Group) SetOrigin(v string) {
	o.Origin = &v
}

// GetPasswordHash returns the PasswordHash field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetPasswordHash() string {
	if o == nil || IsNil(o.PasswordHash) {
		var ret string
		return ret
	}
	return *o.PasswordHash
}

// GetPasswordHashOk returns a tuple with the PasswordHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetPasswordHashOk() (*string, bool) {
	if o == nil || IsNil(o.PasswordHash) {
		return nil, false
	}
	return o.PasswordHash, true
}

// HasPasswordHash returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasPasswordHash() bool {
	if o != nil && !IsNil(o.PasswordHash) {
		return true
	}

	return false
}

// SetPasswordHash gets a reference to the given string and assigns it to the PasswordHash field.
func (o *UserInIdentityV2Group) SetPasswordHash(v string) {
	o.PasswordHash = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *UserInIdentityV2Group) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetProfileValidationRequired returns the ProfileValidationRequired field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetProfileValidationRequired() bool {
	if o == nil || IsNil(o.ProfileValidationRequired) {
		var ret bool
		return ret
	}
	return *o.ProfileValidationRequired
}

// GetProfileValidationRequiredOk returns a tuple with the ProfileValidationRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetProfileValidationRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.ProfileValidationRequired) {
		return nil, false
	}
	return o.ProfileValidationRequired, true
}

// HasProfileValidationRequired returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasProfileValidationRequired() bool {
	if o != nil && !IsNil(o.ProfileValidationRequired) {
		return true
	}

	return false
}

// SetProfileValidationRequired gets a reference to the given bool and assigns it to the ProfileValidationRequired field.
func (o *UserInIdentityV2Group) SetProfileValidationRequired(v bool) {
	o.ProfileValidationRequired = &v
}

// GetResetPasswordSentAt returns the ResetPasswordSentAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetResetPasswordSentAt() time.Time {
	if o == nil || IsNil(o.ResetPasswordSentAt) {
		var ret time.Time
		return ret
	}
	return *o.ResetPasswordSentAt
}

// GetResetPasswordSentAtOk returns a tuple with the ResetPasswordSentAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetResetPasswordSentAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResetPasswordSentAt) {
		return nil, false
	}
	return o.ResetPasswordSentAt, true
}

// HasResetPasswordSentAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasResetPasswordSentAt() bool {
	if o != nil && !IsNil(o.ResetPasswordSentAt) {
		return true
	}

	return false
}

// SetResetPasswordSentAt gets a reference to the given time.Time and assigns it to the ResetPasswordSentAt field.
func (o *UserInIdentityV2Group) SetResetPasswordSentAt(v time.Time) {
	o.ResetPasswordSentAt = &v
}

// GetResetPasswordToken returns the ResetPasswordToken field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetResetPasswordToken() string {
	if o == nil || IsNil(o.ResetPasswordToken) {
		var ret string
		return ret
	}
	return *o.ResetPasswordToken
}

// GetResetPasswordTokenOk returns a tuple with the ResetPasswordToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetResetPasswordTokenOk() (*string, bool) {
	if o == nil || IsNil(o.ResetPasswordToken) {
		return nil, false
	}
	return o.ResetPasswordToken, true
}

// HasResetPasswordToken returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasResetPasswordToken() bool {
	if o != nil && !IsNil(o.ResetPasswordToken) {
		return true
	}

	return false
}

// SetResetPasswordToken gets a reference to the given string and assigns it to the ResetPasswordToken field.
func (o *UserInIdentityV2Group) SetResetPasswordToken(v string) {
	o.ResetPasswordToken = &v
}

// GetSignInCount returns the SignInCount field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetSignInCount() int32 {
	if o == nil || IsNil(o.SignInCount) {
		var ret int32
		return ret
	}
	return *o.SignInCount
}

// GetSignInCountOk returns a tuple with the SignInCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetSignInCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SignInCount) {
		return nil, false
	}
	return o.SignInCount, true
}

// HasSignInCount returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasSignInCount() bool {
	if o != nil && !IsNil(o.SignInCount) {
		return true
	}

	return false
}

// SetSignInCount gets a reference to the given int32 and assigns it to the SignInCount field.
func (o *UserInIdentityV2Group) SetSignInCount(v int32) {
	o.SignInCount = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *UserInIdentityV2Group) SetState(v string) {
	o.State = &v
}

// GetStateChangedAt returns the StateChangedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetStateChangedAt() time.Time {
	if o == nil || IsNil(o.StateChangedAt) {
		var ret time.Time
		return ret
	}
	return *o.StateChangedAt
}

// GetStateChangedAtOk returns a tuple with the StateChangedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetStateChangedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StateChangedAt) {
		return nil, false
	}
	return o.StateChangedAt, true
}

// HasStateChangedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasStateChangedAt() bool {
	if o != nil && !IsNil(o.StateChangedAt) {
		return true
	}

	return false
}

// SetStateChangedAt gets a reference to the given time.Time and assigns it to the StateChangedAt field.
func (o *UserInIdentityV2Group) SetStateChangedAt(v time.Time) {
	o.StateChangedAt = &v
}

// GetStateRegion returns the StateRegion field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetStateRegion() string {
	if o == nil || IsNil(o.StateRegion) {
		var ret string
		return ret
	}
	return *o.StateRegion
}

// GetStateRegionOk returns a tuple with the StateRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetStateRegionOk() (*string, bool) {
	if o == nil || IsNil(o.StateRegion) {
		return nil, false
	}
	return o.StateRegion, true
}

// HasStateRegion returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasStateRegion() bool {
	if o != nil && !IsNil(o.StateRegion) {
		return true
	}

	return false
}

// SetStateRegion gets a reference to the given string and assigns it to the StateRegion field.
func (o *UserInIdentityV2Group) SetStateRegion(v string) {
	o.StateRegion = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetTags() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetTagsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]map[string]interface{} and assigns it to the Tags field.
func (o *UserInIdentityV2Group) SetTags(v map[string]map[string]interface{}) {
	o.Tags = v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *UserInIdentityV2Group) SetTimezone(v string) {
	o.Timezone = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *UserInIdentityV2Group) SetType(v string) {
	o.Type = &v
}

// GetUnlockToken returns the UnlockToken field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetUnlockToken() string {
	if o == nil || IsNil(o.UnlockToken) {
		var ret string
		return ret
	}
	return *o.UnlockToken
}

// GetUnlockTokenOk returns a tuple with the UnlockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetUnlockTokenOk() (*string, bool) {
	if o == nil || IsNil(o.UnlockToken) {
		return nil, false
	}
	return o.UnlockToken, true
}

// HasUnlockToken returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasUnlockToken() bool {
	if o != nil && !IsNil(o.UnlockToken) {
		return true
	}

	return false
}

// SetUnlockToken gets a reference to the given string and assigns it to the UnlockToken field.
func (o *UserInIdentityV2Group) SetUnlockToken(v string) {
	o.UnlockToken = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *UserInIdentityV2Group) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserInIdentityV2Group) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UserInIdentityV2Group) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *UserInIdentityV2Group) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o UserInIdentityV2Group) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInIdentityV2Group) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if !IsNil(o.AccountCspId) {
		toSerialize["account_csp_id"] = o.AccountCspId
	}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.AccountInfobloxId) {
		toSerialize["account_infoblox_id"] = o.AccountInfobloxId
	}
	if !IsNil(o.AgreementsAccepted) {
		toSerialize["agreements_accepted"] = o.AgreementsAccepted
	}
	if !IsNil(o.ApiKey) {
		toSerialize["api_key"] = o.ApiKey
	}
	if !IsNil(o.ApiKeys) {
		toSerialize["api_keys"] = o.ApiKeys
	}
	if !IsNil(o.Approved) {
		toSerialize["approved"] = o.Approved
	}
	if !IsNil(o.Authenticator) {
		toSerialize["authenticator"] = o.Authenticator
	}
	if !IsNil(o.ConfirmToken) {
		toSerialize["confirm_token"] = o.ConfirmToken
	}
	if !IsNil(o.ConfirmationSentAt) {
		toSerialize["confirmation_sent_at"] = o.ConfirmationSentAt
	}
	if !IsNil(o.ConfirmedAt) {
		toSerialize["confirmed_at"] = o.ConfirmedAt
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.CspId) {
		toSerialize["csp_id"] = o.CspId
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.DeletedBy) {
		toSerialize["deleted_by"] = o.DeletedBy
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.FailedAttempts) {
		toSerialize["failed_attempts"] = o.FailedAttempts
	}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.GroupIds) {
		toSerialize["group_ids"] = o.GroupIds
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.JobTitle) {
		toSerialize["job_title"] = o.JobTitle
	}
	if !IsNil(o.LastLogin) {
		toSerialize["last_login"] = o.LastLogin
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.LastValidatedAt) {
		toSerialize["last_validated_at"] = o.LastValidatedAt
	}
	if !IsNil(o.LockedAt) {
		toSerialize["locked_at"] = o.LockedAt
	}
	if !IsNil(o.MarketingOptIn) {
		toSerialize["marketing_opt_in"] = o.MarketingOptIn
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NextRevalidationDueAt) {
		toSerialize["next_revalidation_due_at"] = o.NextRevalidationDueAt
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.PasswordHash) {
		toSerialize["password_hash"] = o.PasswordHash
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if !IsNil(o.ProfileValidationRequired) {
		toSerialize["profile_validation_required"] = o.ProfileValidationRequired
	}
	if !IsNil(o.ResetPasswordSentAt) {
		toSerialize["reset_password_sent_at"] = o.ResetPasswordSentAt
	}
	if !IsNil(o.ResetPasswordToken) {
		toSerialize["reset_password_token"] = o.ResetPasswordToken
	}
	if !IsNil(o.SignInCount) {
		toSerialize["sign_in_count"] = o.SignInCount
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.StateChangedAt) {
		toSerialize["state_changed_at"] = o.StateChangedAt
	}
	if !IsNil(o.StateRegion) {
		toSerialize["state_region"] = o.StateRegion
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UnlockToken) {
		toSerialize["unlock_token"] = o.UnlockToken
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UserInIdentityV2Group) UnmarshalJSON(data []byte) (err error) {
	varUserInIdentityV2Group := _UserInIdentityV2Group{}

	err = json.Unmarshal(data, &varUserInIdentityV2Group)

	if err != nil {
		return err
	}

	*o = UserInIdentityV2Group(varUserInIdentityV2Group)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "account_csp_id")
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "account_infoblox_id")
		delete(additionalProperties, "agreements_accepted")
		delete(additionalProperties, "api_key")
		delete(additionalProperties, "api_keys")
		delete(additionalProperties, "approved")
		delete(additionalProperties, "authenticator")
		delete(additionalProperties, "confirm_token")
		delete(additionalProperties, "confirmation_sent_at")
		delete(additionalProperties, "confirmed_at")
		delete(additionalProperties, "country")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "csp_id")
		delete(additionalProperties, "deleted_at")
		delete(additionalProperties, "deleted_by")
		delete(additionalProperties, "email")
		delete(additionalProperties, "failed_attempts")
		delete(additionalProperties, "first_name")
		delete(additionalProperties, "group_ids")
		delete(additionalProperties, "id")
		delete(additionalProperties, "job_title")
		delete(additionalProperties, "last_login")
		delete(additionalProperties, "last_name")
		delete(additionalProperties, "last_validated_at")
		delete(additionalProperties, "locked_at")
		delete(additionalProperties, "marketing_opt_in")
		delete(additionalProperties, "name")
		delete(additionalProperties, "next_revalidation_due_at")
		delete(additionalProperties, "origin")
		delete(additionalProperties, "password_hash")
		delete(additionalProperties, "phone_number")
		delete(additionalProperties, "profile_validation_required")
		delete(additionalProperties, "reset_password_sent_at")
		delete(additionalProperties, "reset_password_token")
		delete(additionalProperties, "sign_in_count")
		delete(additionalProperties, "state")
		delete(additionalProperties, "state_changed_at")
		delete(additionalProperties, "state_region")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "timezone")
		delete(additionalProperties, "type")
		delete(additionalProperties, "unlock_token")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUserInIdentityV2Group struct {
	value *UserInIdentityV2Group
	isSet bool
}

func (v NullableUserInIdentityV2Group) Get() *UserInIdentityV2Group {
	return v.value
}

func (v *NullableUserInIdentityV2Group) Set(val *UserInIdentityV2Group) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInIdentityV2Group) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInIdentityV2Group) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInIdentityV2Group(val *UserInIdentityV2Group) *NullableUserInIdentityV2Group {
	return &NullableUserInIdentityV2Group{value: val, isSet: true}
}

func (v NullableUserInIdentityV2Group) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInIdentityV2Group) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
